### ISSUE TITLE
Local build of Docker image gives permissions issue in the pip install step

### ISSUE THREAD

**Issue by ishaileshpant** [intel/openfl#1056]
Local build of Docker image throws permission denied / file node found issue on "/home/openfl/" file(s) limiting local docker build / test and local trivy scans

Possibly an issue with "COPY" command on src folder to docker build context for "openfl" user home folder
![Screenshot 2024-09-19 140429](https://github.com/user-attachments/assets/75a8a666-6abc-45f0-940e-71177d3a1a23)

**Comment by theakshaypant** [comment]
Closed with #1078
