### ISSUE TITLE
`fx model save` errors when taskrunner is initialized with `--input_shape` without a local dataset present

### ISSUE THREAD

**Issue by kminhta** [intel/openfl#1080]
**Describe the bug**
PR #983 enabled `--input_shape` to be passed into `fx plan initialize`. This allowed the task runner to initialize model weights using a manually specified input shape rather than having to run a local dataset through the workspace's dataloader to automatically extract data information

However, in order to save the final model weights in its native format, `fx model save` requires the task runner to be reinitialized and loaded with the model protobuf [[ref](https://github.com/securefederatedai/openfl/blob/develop/openfl/interface/model.py#L74)].

Because the default option for initializing the task runner is to load in a local dataset, this will error out with:

```
FileNotFoundError: [Errno 2] No such file or directory <local_data_dir>
```

**Ask**: `fx model save` should be allowed to pass `--input_shape` and/or default to the args used during the original execution of `fx plan initialize` 

**To Reproduce**
1. `fx workspace create --template <template> --prefix <workspace_name>`
2. `cd <workspace_name>`
3. `fx plan initialize --input_shape <shape>`
4. `fx model save --input <path to init pbuf> --output <path to output>`

**Expected behavior**
Model should save in the specified output file path

**Comment by bsenthilr** [comment]
https://github.com/securefederatedai/openfl/pull/1076/files
