### ISSUE TITLE
Creation of OpenFL image using Dockerfile.base fails for openfl user

### ISSUE THREAD

**Issue by noopurintel** [intel/openfl#1082]
**Describe the bug**
`Permission denied` error while trying to run `Dockerfile.base` as part of [this step](https://openfl.readthedocs.io/en/latest/get_started/installation.html#productname-with-docker) which uses a fresh `openfl` user at runtime.

**To Reproduce**
1. Setup virtual environment for python on given machine.
2. Install dependencies like pip, setuptools and wheel etc.
3. Git clone openfl repository and install the packages as part of it.
4. Run "fx" command and validate the successful output.
5. Run below command to create an image.

`docker build -f openfl-docker/Dockerfile.base .`

**Expected behavior**
Successful creation of docker image.

**Screenshots**

<img width="1324" alt="image" src="https://github.com/user-attachments/assets/5ab2e854-a5d3-4686-a2d7-54c6cf5b88e6">

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04.6 LTS

**Additional context**
If we comment out the user and group creation part and rather use an existing user, it works fine.

<img width="1324" alt="image" src="https://github.com/user-attachments/assets/4598e23d-8ddc-4cc3-bd82-be5d5c642b2f">

**Comment by theakshaypant** [comment]
Looks like a duplicate of #1056. 

@ishaileshpant has raised a PR with a potential fix #1078.

**Comment by noopurintel** [comment]
Closing the issue.
