### ISSUE TITLE
OpenFL installation in windows fails if longpath is not enabled

### ISSUE THREAD

**Issue by ishaileshpant** [intel/openfl#1086]
- Minor issue related to documentation/pre-requisite step for windows as openfl install via
```
pip install openfl
``` 
fails complaining of LongPath not enabled (which is the case in default in windows)
```
Using cached openfl-1.6-py3-none-any.whl (11.8 MB)
Installing collected packages: openfl
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\***\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openfl-tutorials\\experimental\\Vertical_FL\\Workflow_Interface_VFL_Two_Party_Workspace_Creation_from_JupyterNotebook.ipynb'
HINT: This error might have occurred since this system does not have Windows Long Path support enabled. You can find information on how to enable this at https://pip.pypa.io/warnings/enable-long-paths
```

Solution:

Either use Registry editor or powershell to edit this entry - set to 1 (default 0)
```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem]
"LongPathsEnabled"=dword:00000001
```

**Comment by MasterSkepticista** [comment]
A framework should not suggest registry edits, unless absolutely required.
The path shown, even assuming reasonable username size would be 270-280 characters (10-20 characters above Windows limit). 

The file name alone is 72 characters (wasting a third of the limit). A better solution is to rename `Workflow_Interface_VFL_Two_Party_Workspace_Creation_from_JupyterNotebook.ipynb
` to `TwoPartyWorkspaceCreation.ipynb`

Given the directory structure (and notebook readme) it will be obvious to the user that:
1. It is a workflow interface example
2. It is for VFL
3. It is a jupyter notebook

**Comment by MasterSkepticista** [comment]
Oops, let me do a PR and then close.
