### ISSUE TITLE
Some of important links are broken in GOVERNANCE.md

### ISSUE THREAD

**Issue by grib0ed0v** [intel/openfl#1119]
_[Candidate for Good First Issue]_

In [GOVERNANCE.MD](https://github.com/securefederatedai/openfl/blob/develop/GOVERNANCE.md) some of important links are broken. 

For example: 
The current list of TSC members is [here](https://github.com/securefederatedai/openfl/TSC).

Easy to fix, since the file exists and you just need to correct the link: 
The current list of TSC members is [here](https://github.com/securefederatedai/openfl/blob/develop/TSC.md).

But, maybe, it's a good idea not just fix this, but also update other `.md` docs as well.

**Comment by MasterSkepticista** [comment]
Thanks for pointing this out @grib0ed0v. We'll check other impacted files.

**Comment by rajithkrishnegowda** [comment]
fixed in this [https://github.com/securefederatedai/openfl/pull/1175](PR)

**Comment by rajithkrishnegowda** [comment]
fixed in PR  [https://github.com/securefederatedai/openfl/pull/1175]
