### ISSUE TITLE
TaskRunner Federation - one or more collaborators failing to connect to aggregator

### ISSUE THREAD

**Issue by noopurintel** [intel/openfl#1163]
**Describe the bug**
First of all, this is an intermittent issue irrespective of the model or python version being used for the federation run.
From last few (4-5) days, we are observing this problem where one of the collaborators is unable to connect to the aggregator, whereas another collaborator connects and receives the tasks from aggregator quickly.
This results in all the participants just waiting after the first round.

Also, this has been observed mostly on GitHub as part of nightly runs. For instance - https://github.com/noopurintel/openfl/actions/runs/11927821340

**To Reproduce**
Unable to reproduce it locally. But, it keeps failing as part of the [Task Runner E2E](https://github.com/securefederatedai/openfl/actions/workflows/task_runner_e2e.yml) GitHub workflow.

It worked fine till the commit - 63177f4113b616c76ab94bb910a5d3977f3919df and started failing later.

**Expected behavior**
Collaborators should be able to connect to aggregator and federation run should happen smoothly.

**Machine:**
 Ubuntu 22.04

**Artifacts:**
Sharing the aggregator and collaborator logs from one of the runs (model torch_cnn_mnist and python 3.10)

[aggregator.log](https://github.com/user-attachments/files/17826573/aggregator.log)

[collaborator1.log](https://github.com/user-attachments/files/17826576/collaborator1.log)

[collaborator2.log](https://github.com/user-attachments/files/17826578/collaborator2.log)

**Comment by MasterSkepticista** [comment]
@noopurintel I don't see evidence of this issue on tip of develop.
I tested both pytest and my local bash setup for up to 16 collaborators. All CI tests on new PRs seem to pass.

Could you provide a minimum reproducible example? I suspect failures in our internal openfl-security fork is due to stale processes and/or test delays, since CI and local tests all pass.

**Comment by noopurintel** [comment]
@MasterSkepticista - I believe we discussed after your comment above, and the issue was there on GitHub runs, quite random though.
Meanwhile, only one CI test from the PR pipeline seems to run with 2 collaborators, all others are running with single collaborator and thus the issue might not have occurred.
