### ISSUE TITLE
Poor error traceback

### ISSUE THREAD

**Issue by katerina-merkulova** [intel/openfl#142]
When I have some errors in my code running federation, I get only the error without full traceback with call stack. For example: `[17:46:46] ERROR Collaborator failed: list index out of range` . And I have no way of knowing where specifically error is. I only have a message above and link to https://github.com/intel/openfl/blob/c2796b6c3a425436d38c3b3b7f8867e2ea4f9918/openfl/component/envoy/envoy.py#L59

**Comment by psfoley** [comment]
Hi @katerina-merkulova, thanks for filing this issue. The director / envoy is nearly finalized, but there are still a couple of minor bugs we are working out before our next tagged release (OpenFL 1.2). I have added more informative logging to this [list of areas to prioritize](https://github.com/intel/openfl/issues/128)
