### ISSUE TITLE
openfl package not found

### ISSUE THREAD

**Issue by alexkarargyris** [intel/openfl#16]
**Describe the bug**
Following the OpenFL documentation instructions [here](https://openfl.readthedocs.io/en/latest/install.initial.html#initial-steps) but I get the following error when running `pip install openfl`:

`
ERROR: Could not find a version that satisfies the requirement openfl
`
`
ERROR: No matching distribution found for openfl
`

-OS: MacOS Big Sur

**Comment by alexey-gruzdev** [comment]
@alexkarargyris thanks for pointing this out. Right now we didn't publish PyPI wheels (this activity is in progress), so you need to install OpenFL from source:
```
git clone https://github.com/intel/openfl.git
cd openfl/
pip install .
```
