### ISSUE TITLE
Requirements for ShardDescriptor are installing separatly from openfl requirements.

### ISSUE THREAD

**Issue by dmitryagapov** [intel/openfl#160]
**Describe the bug**
To run envoy we need to install extra requirements that are not installing with openfl.

**To Reproduce**
1. clone openfl
2. cd openfl
3. pip install -e .
4. cd openfl-tutorials/interactive_api/Director_Pytorch_Kvasir_UNET/envoy_folder
5. source ./start_envoy.sh
6. envoy return error

**Expected behavior**
envoy is working correct

**Comment by alexey-gruzdev** [comment]
Closed this per discussion with @dmitryagapov , since it looks like separation of requirements is natural due to running on different machines.
