### ISSUE TITLE
Experiment order in Director

### ISSUE THREAD

**Issue by dmitryagapov** [intel/openfl#168]
**Is your feature request related to a problem? Please describe.**
When experiment is set on director, director instantly creates and runs aggregator. Will be better if only one aggregator is run at one time. 

**Describe the solution you'd like**
Create structure for experiment.
Create dict, list or queue for experiments.

**Comment by alexey-gruzdev** [comment]
Actually this one was closed via https://github.com/intel/openfl/pull/188/ .
