### ISSUE TITLE
Traceback lost

### ISSUE THREAD

**Issue by igor-davidyuk** [intel/openfl#171]
This line may suppress traceback for exceptions.
https://github.com/intel/openfl/blob/aed8452b12d20dcc80bd722336246d679fa41484/openfl/component/envoy/envoy.py#L68

Regardless, OpenFL could do better by forwarding exceptions and tracebacks from aggregator and collaborator to the Frontend client

**Comment by ishaileshpant** [comment]
@igor-davidyuk thanks for raising this concern, ideally, we should be enabling trace back either at global logging level so that all such cases, specifically in debug/dev setup, traces are not missing

**Comment by teoparvanov** [comment]
Closing this as the Interactive API has been deprecated.
