### ISSUE TITLE
Differential Privacy example via new Interactive API

### ISSUE THREAD

**Issue by alexey-gruzdev** [intel/openfl#175]
It would be great to add _Differential Privacy_ example to our existing tutorials, just to show exact place (**ShardDescriptor** class), where user need to put DP logic.

**Comment by CasellaJr** [comment]
News about this? @psfoley @mansishr

**Comment by teoparvanov** [comment]
Closing this issue, as the Interactive API is being deprecated in favor of Workflow API. In parallel, we have started considering how DP could be more deeply integrated as a feature of OpenFL (rather than just example code).
