### ISSUE TITLE
Pin versions of packages 

### ISSUE THREAD

**Issue by alexey-gruzdev** [intel/openfl#182]
We need to ping all unpinned versions of packages in setup.py & workspace environments.

**Comment by psfoley** [comment]
@alexey-gruzdev is this about decreasing dependency solving time during installation? Pinning versions of packages makes it harder to integrate other frameworks with OpenFL. Package conflicts have already come up during previous integration efforts ([MLCube](https://github.com/mlcommons/mlcube/blob/master/mlcube/requirements.txt), Frontier Development Lab - CRISP framework), so unless there is a fixed security vulnerability or API that is tied to a particular subpackage, we should try to stay as flexible as possible

**Comment by alexey-gruzdev** [comment]
Initially, we meant to solve an envoy environment degradation (a lot of experiment-specific packages with their dependencies installed one by one). I would close this with opening another issue.
