### ISSUE TITLE
Envoy's Python environment degradation when do multiple experiments within the same Federation

### ISSUE THREAD

**Issue by alexey-gruzdev** [intel/openfl#189]
When we run multiple experiments (could be TF, then PyTorch, then old TF or PyTorch) within the same Federation, envoy's environment is started to degrade. Probably, the solution could be to create a separate environment for each experiment, or clean up the environment when experiment ended.

On Envoy when the Experiment is finished the gpu memory still allocated.

**Comment by teoparvanov** [comment]
Closing this as the Interactive API has been deprecated.
