### ISSUE TITLE
Redesign protobuf messages

### ISSUE THREAD

**Issue by dmitryagapov** [intel/openfl#195]
- [x] define messages as ``` rpc <RpcName> (<RpcName>Request) retunns (<RpcName>Response) {}```
 - [x] redesign `ShardInfo`, `ExperimentData`, `ExperimentInfo`, `CollaboratorStatus`, `ShardAcknowledgement`

**Comment by igor-davidyuk** [comment]
+ compilation problems
+ rewrite federation.proto compliant to proto3 syntax

**Comment by alexey-gruzdev** [comment]
Resolved via #296
