### ISSUE TITLE
Dead link in the README

### ISSUE THREAD

**Issue by GMTSE** [intel/openfl#217]
Hi,

FYI, The link to the notebooks (for starters with the platform) in the README (https://openfl.readthedocs.io/en/latest/running_the_federation.notebook.html) is wrong.

Have a nice day

**Comment by alexey-gruzdev** [comment]
Hi @GMTSE, thanks for the interest and to bring this up. Fixed via https://github.com/intel/openfl/commit/f2e59b3004a32543b6af31b24d137b47dff854b4 .
