### ISSUE TITLE
Reproducing the Director-Envoy notebook on DevCloud

### ISSUE THREAD

**Issue by saransh09** [intel/openfl#221]
I am trying to reproduce the director-envoy notebook on DevCloud for a demo. There is a strange behavior that I have come across. One of the envoy starts training, but other one fails for some reason. I am adding the traceback of the error down below. If someone knows why that is happening, could you please let me know?

plan.py:176
[04:28:34] ERROR    Collaborator failed with error: unsupported pickle protocol: 5:                                                                  envoy.py:69
                    Traceback (most recent call last):                                                                                                          
                      File "/home/uxxxx/.local/lib/python3.7/site-packages/openfl/component/envoy/envoy.py", line 67, in run                                   
                        self._run_collaborator()                                                                                                                
                      File "/home/uxxxx/.local/lib/python3.7/site-packages/openfl/component/envoy/envoy.py", line 104, in _run_collaborator                    
                        self.certificate, shard_descriptor=self.shard_descriptor)                                                                               
                      File "/home/uxxxx/.local/lib/python3.7/site-packages/openfl/federated/plan/plan.py", line 427, in get_collaborator                       
                        model_provider, task_keeper, data_loader = self.deserialize_interface_objects()                                                         
                      File "/home/uxxxx/.local/lib/python3.7/site-packages/openfl/federated/plan/plan.py", line 536, in                                        
                    deserialize_interface_objects                                                                                                               
                        for filename in filenames                                                                                                               
                      File "/home/uxxxx/.local/lib/python3.7/site-packages/openfl/federated/plan/plan.py", line 536, in <listcomp>                             
                        for filename in filenames                                                                                                               
                      File "/home/uxxxx/.local/lib/python3.7/site-packages/openfl/plugins/interface_serializer/cloudpickle_serializer.py", line 27,            
                    in restore_object                                                                                                                           
                        return cloudpickle.load(f)                                                                                                              
                    ValueError: unsupported pickle protocol: 5                                                                                                  
           INFO     Send WaitExperiment request                                                                                            director_client.py:72
           INFO     WaitExperiment response has received                                                                                   director_client.py:74
[04:36:48] ERROR    Failed to get experiment: <_MultiThreadedRendezvous of RPC that terminated with:                                                 envoy.py:58
                            status = StatusCode.UNAVAILABLE                                                                                                     
                            details = "Socket closed"                                                                                                           
                            debug_error_string = "{"created":"@1635939408.195000784","description":"Error received from peer                                    
                    ipv4:10.9.1.100:50051","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"             
                    >                                                                                                                                           
                    Traceback (most recent call last):                                                                                                          
                      File "/home/uxxxx/.local/lib/python3.7/site-packages/openfl/component/envoy/envoy.py", line 55, in run                                   
                        experiment_name = self.director_client.wait_experiment()                                                                                
                      File "/home/uxxxx/.local/lib/python3.7/site-packages/openfl/transport/grpc/director_client.py", line 75, in wait_experiment              
                        response = next(response_iter)                                                                                                          
                      File "/home/uuxxxx/.local/lib/python3.7/site-packages/grpc/_channel.py", line 416, in __next__                                            
                        return self._next()                                                                                                                     
                      File "/home/uxxxx/.local/lib/python3.7/site-packages/grpc/_channel.py", line 803, in _next                                               
                        raise self                                                                                                                              
                    grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:                                              
                            status = StatusCode.UNAVAILABLE                                                                                                     
                            details = "Socket closed"                                                                                                           
                            debug_error_string = "{"created":"@1635939408.195000784","description":"Error received from peer                                    
                    ipv4:10.9.1.100:50051","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"             
                    >                                                                                                                                           

########################################################################
# End of output for job 1007752.v-qsvr-1.aidevcloud
# Date: Wed 03 Nov 2021 04:36:50 AM PDT
########################################################################

I have ensured that the director and the two envoys are actually on a separate machine. I don't exactly understand what could the reason be.

**Comment by alexey-gruzdev** [comment]
@saransh09 which particular example you are trying to use?

**Comment by saransh09** [comment]
> @saransh09 which particular example you are trying to use?

https://github.com/intel/openfl/tree/develop/openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet

**Comment by alexey-gruzdev** [comment]
@saransh09 let's try to see if we are achieving the same behaviour with Python 3.8. Keep us updated.

**Comment by saransh09** [comment]
> @saransh09 let's try to see if we are achieving the same behaviour with Python 3.8. Keep us updated.

           INFO     Building 🡆 Object CloudpickleSerializer from openfl.plugins.interface_serializer.cloudpickle_serializer Module.                  plan.py:170
           INFO     Settings 🡆 {}                                                                                                                    plan.py:173
           INFO     Override 🡆 {}                                                                                                                    plan.py:175
[02:16:02] ERROR    Collaborator failed with error: an integer is required (got type bytes):                                                         envoy.py:69
                    Traceback (most recent call last):                                                                                                          
                      File "/home/u71711/.conda/envs/python38/lib/python3.8/site-packages/openfl/component/envoy/envoy.py", line 67, in run                     
                        self._run_collaborator()                                                                                                                
                      File "/home/u71711/.conda/envs/python38/lib/python3.8/site-packages/openfl/component/envoy/envoy.py", line 103, in                        
                    _run_collaborator                                                                                                                           
                        col = plan.get_collaborator(self.name, self.root_certificate, self.private_key,                                                         
                      File "/home/u71711/.conda/envs/python38/lib/python3.8/site-packages/openfl/federated/plan/plan.py", line 427, in                          
                    get_collaborator                                                                                                                            
                        model_provider, task_keeper, data_loader = self.deserialize_interface_objects()                                                         
                      File "/home/u71711/.conda/envs/python38/lib/python3.8/site-packages/openfl/federated/plan/plan.py", line 534, in                          
                    deserialize_interface_objects                                                                                                               
                        interface_objects = [                                                                                                                   
                      File "/home/u71711/.conda/envs/python38/lib/python3.8/site-packages/openfl/federated/plan/plan.py", line 535, in <listcomp>               
                        serializer.restore_object(self.config['api_layer']['settings'][filename])                                                               
                      File                                                                                                                                      
                    "/home/u71711/.conda/envs/python38/lib/python3.8/site-packages/openfl/plugins/interface_serializer/cloudpickle_serializer.py",              
                    line 27, in restore_object                                                                                                                  
                        return cloudpickle.load(f)                                                                                                              
                    TypeError: an integer is required (got type bytes)

**Comment by alexey-gruzdev** [comment]
@saransh09 any modifications to code of the example? Any comments from DevCloud team? I wonder if you would change machines in devcloud and see the same behaviour

**Comment by saransh09** [comment]
Sorry for the delay

I am pasting the traceback of the exact problem, I tried to segregate and repeat the experiment in a different environment : 

ERROR: Could not find a version that satisfies the requirement cfxmagic==0.1.dev0 (from versions: none)
ERROR: No matching distribution found for cfxmagic==0.1.dev0
[02:05:48] ERROR    Failed to install requirements: Command '['/home/u71711/.conda/envs/py38/bin/python', '-m', 'pip', 'install', '-r',          workspace.py:46
                    '/home/u71711/demo_openf12/envoy_2/kvasir_test_experiment/requirements.txt']' returned non-zero exit status 1.                              
[02:05:53] INFO     FL-Plan hash is 7a28389c40262921ad82ab9c8ded1d9fec90785eb6ed7b32b392c8474f4e44d2ca6ccf7932db67099ef20c4ba5e0faba                 plan.py:232
           INFO     FL-Plan hash is 7a28389c40262921ad82ab9c8ded1d9fec90785eb6ed7b32b392c8474f4e44d2ca6ccf7932db67099ef20c4ba5e0faba                 plan.py:232
           INFO     Parsing Federated Learning Plan : SUCCESS : plan/plan.yaml.                                                                      plan.py:141
           INFO     aggregator:                                                                                                                      plan.py:145
                      settings:                                                                                                                                 
                        best_state_path: save/best.pbuf                                                                                                         
                        db_store_rounds: 1                                                                                                                      
                        init_state_path: save/init.pbuf                                                                                                         
                        last_state_path: save/last.pbuf                                                                                                         
                        rounds_to_train: 2                                                                                                                      
                      template: openfl.component.Aggregator                                                                                                     
                    api_layer:                                                                                                                                  
                      required_plugin_components:                                                                                                               
                        serializer_plugin: openfl.plugins.interface_serializer.cloudpickle_serializer.CloudpickleSerializer                                     
                      settings:                                                                                                                                 
                        aggregation_function_interface_file: aggregation_function_obj.pkl                                                                       
                        dataloader_interface_file: loader_obj.pkl                                                                                               
                        model_interface_file: model_obj.pkl                                                                                                     
                        tasks_interface_file: tasks_obj.pkl                                                                                                     
                    assigner:                                                                                                                                   
                      settings:                                                                                                                                 
                        task_groups:                                                                                                                            
                        - name: train_and_validate                                                                                                              
                          percentage: 1.0                                                                                                                       
                          tasks:                                                                                                                                
                          - train                                                                                                                               
                          - localy_tuned_model_validate                                                                                                         
                          - aggregated_model_validate                                                                                                           
                      template: openfl.component.RandomGroupedAssigner                                                                                          
                    collaborator:                                                                                                                               
                      settings:                                                                                                                                 
                        db_store_rounds: 1                                                                                                                      
                        delta_updates: false                                                                                                                    
                        device_assignment_policy: CPU_ONLY                                                                                                      
                        opt_treatment: CONTINUE_GLOBAL                                                                                                          
                      template: openfl.component.Collaborator                                                                                                   
                    data_loader:                                                                                                                                
                      settings:                                                                                                                                 
                        train_bs: 4                                                                                                                             
                        valid_bs: 8                                                                                                                             
                      template: openfl.federated.DataLoader                                                                                                     
                    network:                                                                                                                                    
                      settings:                                                                                                                                 
                        agg_addr: s001-n120.aidevcloud                                                                                                          
                        agg_port: 57365                                                                                                                         
                        cert_folder: cert                                                                                                                       
                        client_reconnect_interval: 5                                                                                                            
                        disable_client_auth: false                                                                                                              
                        hash_salt: auto                                                                                                                         
                        tls: false                                                                                                                              
                      template: openfl.federation.Network                                                                                                       
                    task_runner:                                                                                                                                
                      required_plugin_components:                                                                                                               
                        framework_adapters: openfl.plugins.frameworks_adapters.pytorch_adapter.FrameworkAdapterPlugin                                           
                      settings: {}                                                                                                                              
                      template: openfl.federated.task.task_runner.CoreTaskRunner                                                                                
                    tasks:                                                                                                                                      
                      aggregated_model_validate:                                                                                                                
                        function: validate                                                                                                                      
                        kwargs:                                                                                                                                 
                          apply: global                                                                                                                         
                      localy_tuned_model_validate:                                                                                                              
                        function: validate                                                                                                                      
                        kwargs:                                                                                                                                 
                          apply: local                                                                                                                          
                      settings: {}                                                                                                                              
                      train:                                                                                                                                    
                        function: train                                                                                                                         
                        kwargs:                                                                                                                                 
                          some_parameter: 42                                                                                                                    
                                                                                                                                                                
Data = {}
           INFO     🧿 Starting a Collaborator Service.                                                                                             envoy.py:101
           INFO     Building 🡆 Object CloudpickleSerializer from openfl.plugins.interface_serializer.cloudpickle_serializer Module.                  plan.py:170
           INFO     Settings 🡆 {}                                                                                                                    plan.py:173
           INFO     Override 🡆 {}                                                                                                                    plan.py:175
[02:05:56] ERROR    Collaborator failed with error: an integer is required (got type bytes):                                                         envoy.py:69
                    Traceback (most recent call last):                                                                                                          
                      File "/home/u71711/.conda/envs/py38/lib/python3.8/site-packages/openfl/component/envoy/envoy.py", line 67, in run                         
                        self._run_collaborator()                                                                                                                
                      File "/home/u71711/.conda/envs/py38/lib/python3.8/site-packages/openfl/component/envoy/envoy.py", line 103, in                            
                    _run_collaborator                                                                                                                           
                        col = plan.get_collaborator(self.name, self.root_certificate, self.private_key,                                                         
                      File "/home/u71711/.conda/envs/py38/lib/python3.8/site-packages/openfl/federated/plan/plan.py", line 435, in get_collaborator             
                        model_provider, task_keeper, data_loader = self.deserialize_interface_objects()                                                         
                      File "/home/u71711/.conda/envs/py38/lib/python3.8/site-packages/openfl/federated/plan/plan.py", line 541, in <genexpr>                    
                        return (self.restore_object(api_layer['settings'][filename]) for filename in filenames)                                                 
                      File "/home/u71711/.conda/envs/py38/lib/python3.8/site-packages/openfl/federated/plan/plan.py", line 561, in restore_object               
                        obj = serializer_plugin.restore_object(filename)                                                                                        
                      File                                                                                                                                      
                    "/home/u71711/.conda/envs/py38/lib/python3.8/site-packages/openfl/plugins/interface_serializer/cloudpickle_serializer.py", line             
                    27, in restore_object                                                                                                                       
                        return cloudpickle.load(f)                                                                                                              
                    TypeError: an integer is required (got type bytes)                                                                                          
           INFO     Send WaitExperiment request                                                                                            director_client.py:72
           INFO     WaitExperiment response has received                                                                                   director_client.py:74


There seems to be an issue with the library cfxmagic and trying to install it on DevCloud. 

After some googling, I found this : https://community.intel.com/t5/Intel-DevCloud/cfxmagic-module-not-found-error/td-p/1174141

There was no conclusive workaround to this that was posted. Therefore, I will loop in the DevCloud team into this. 

Closing the issue for now
