### ISSUE TITLE
Workspace env hasn't installed Tensorflow, therefore envoy hasn't it too

### ISSUE THREAD

**Issue by katerina-merkulova** [intel/openfl#241]
When I install dependencies in the notebook, then there're not seen by `freeze` in python:
https://github.com/intel/openfl/blob/050b8354b698a34b5ef01f0f55f968f52f63f84d/openfl/interface/interactive_api/experiment.py#L182

So, it triggers `ModuleNotFoundError: No module named 'tensorflow'` on the envoy. After restarting the kernel and the federation, if it is running, everything is fine.

However, we can avoid it by using cmd `freeze`, which doesn't have this problem.

To reproduce on a clean environment with OpenFL only, in the notebook run:
~~~
!pip install tensorflow==2.5.1

from pip._internal.operations import freeze
list(freeze.freeze())
~~~

P.S. With PyTorch everything works fine.

**Comment by katerina-merkulova** [comment]
Python 3.8.10
pip 20.0.2
jupyter 1.0.0

**Comment by teoparvanov** [comment]
Closing this issue, as the Interactive API is being deprecated in favor of Workflow API.
