### ISSUE TITLE
Error while running the kvasir interactive API example

### ISSUE THREAD

**Issue by shreyasnc1** [intel/openfl#246]
**Describe the bug**
Error while running the kvasir interactive API example

**To Reproduce**
1) Use openfl 1.2 and Pytorch_kvasir interactive API tutorial
2) Start Director
3) Start Envoy
4) After dataset is download, there is an error

**Expected behavior**
Federation should start

**Screenshots**
![image](https://user-images.githubusercontent.com/84725834/143205551-4d499c51-3ca8-4000-9112-0c63155d3e4b.png)

Note:

using Ubuntu 20.04. The ports 50500 are open and the same was verified through netcat command

**Comment by alexey-gruzdev** [comment]
@shreyasnc1 could you please post the commands that you are using for starting the director/envoy?

**Comment by shreyasnc1** [comment]
Director:
fx director start --disable-tls -c director_config.yaml

Envoy:
fx envoy start -n env_one --disable-tls --envoy-config-path envoy_config.yaml -dh localhost -dp 50050


envoy_config.yaml has:
-----------
(myenv) snc@vsglab-S2600WFQ:~/snc/openfl/openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/envoy$ cat envoy_config.yaml
params:
  cuda_devices: [0,2]

optional_plugin_components:
 cuda_device_monitor:
   template: openfl.plugins.processing_units_monitor.pynvml_monitor.PynvmlCUDADeviceMonitor
   settings: []

shard_descriptor:
  template: kvasir_shard_descriptor.KvasirShardDescriptor
  params:
    data_folder: kvasir_data
    rank_worldsize: 1,10
    enforce_image_hw: '300,400'
    -----

**Comment by alexey-gruzdev** [comment]
@shreyasnc1 Could you please also post a `director_config.yaml` as well?

**Comment by shreyasnc1** [comment]
settings:
  listen_host: localhost
  listen_port: 50050
  sample_shape: ['300', '400', '3']
  target_shape: ['300', '400']
  envoy_health_check_period: 5  # in seconds
~
~

We are running federation on the same machine

**Comment by alexey-gruzdev** [comment]
My initial guess is that with version 1.2 (if you are installing this from PyPI by using `pip install openfl`) you also need to use the v1.2 of tutorial - https://github.com/intel/openfl/blob/v1.2/openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/envoy/shard_config.yaml . Shard config in that case doesn't have `optional_plugin_components` section

**Comment by alexey-gruzdev** [comment]
@shreyasnc1 I've checked v1.2 on my machine and v1.2 tag for tutorial files. So it looks like you need to change port to 50050 [in the running script](https://github.com/intel/openfl/blob/v1.2/openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/envoy/start_envoy.sh) And Envoy could connect to the Director in this scenario

**Comment by shreyasnc1** [comment]
@alexey-gruzdev 

I did the change, but didnt help :(

![image](https://user-images.githubusercontent.com/84725834/143209104-4342215a-48f1-43cf-aad6-f9fd14b5bd32.png)
![image](https://user-images.githubusercontent.com/84725834/143209168-d695fd9b-da23-42d1-99cc-88c522e874f9.png)


Contents of shard_config.yaml:

(myenv) snc@vsglab-S2600WFQ:~/snc/openfl/openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/envoy$ cat shard_config.yaml
template: kvasir_shard_descriptor.KvasirShardDescriptor
params:
  data_folder: kvasir_data
  rank_worldsize: 1,90
  enforce_image_hw: '300,400'(
  
  
  Note: I did ufw allow to enable the port 50050. Anything else that I must do?
  I am using 1.2 tag now

**Comment by shreyasnc1** [comment]
@alexey-gruzdev  the issue was because of the intel proxy I had set .
unset http_proxy; unset https_proxy helped. 

thanks

**Comment by shreyasnc1** [comment]
@alexey-gruzdev  The experiment continues on both director and envoy, but in the workspace I see this error:

Director:
![image](https://user-images.githubusercontent.com/84725834/143383483-c1b92457-945b-4062-8a34-01b8db313ed4.png)

Envoy
![image](https://user-images.githubusercontent.com/84725834/143383544-2097f654-077d-48f2-abe6-4c7e2ef329e9.png)

Workspace(running experiment)

![image](https://user-images.githubusercontent.com/84725834/143383595-316b7839-6661-470d-8e1e-39ae41e2cd0e.png)

Proxy is disabled
![image](https://user-images.githubusercontent.com/84725834/143383641-ed35b8bd-8e1e-49f8-b607-54e64c16b94d.png)

**Comment by shreyasnc1** [comment]
CLosing the issue as the issue is looking like an env issue
