### ISSUE TITLE
OpenFL, Ability to run scripts offline, without internet

### ISSUE THREAD

**Issue by rlmcgech-intel** [intel/openfl#275]
Federal and Aerospace - Cybersecurity Demo Platform (CDP)

CDP OpenFL use case

Fortress Peak is a demo system that is not on the internet.   Currently OpenFL scripts download training data from the internet.    Need to remove all dependencies on the internet.

Cross reference with CDP req FAREQ-100

**Comment by psfoley** [comment]
@rlmcgech-intel while some of the provided OpenFL examples rely on public datasets, OpenFL running on a single node has no dependence on an external connection if local datasets are available.
