### ISSUE TITLE
OpenFL needs to support Keras, Pytorch and TensorFlow frameworks

### ISSUE THREAD

**Issue by rlmcgech-intel** [intel/openfl#276]
Federal and Aerospace - Cybersecurity Demo Platform (CDP)

CDP OpenFL use case

Cross reference with CDP req FAREQ-102

**Comment by psfoley** [comment]
Thanks @rlmcgech-intel for submitting this issue. Keras, Pytorch, and Tensorflow are all supported today in OpenFL.
