### ISSUE TITLE
Same data shard on multiple envoys when using shard descriptor with random data splitter

### ISSUE THREAD

**Issue by mansishr** [intel/openfl#282]
**Describe the bug**
When using shard descriptor with data splitter functionality (kvasir_shard_descriptor_with_data_splitter.py), the same data shard is appearing across multiple envoys. This is because the split function to shard the dataset (RandomNumpyDataSplitter) is being called on every envoy, causing the split to occur on every envoy. https://github.com/intel/openfl/blob/b60cbfbdad595e653c94cee23fd35add993b94b0/openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/envoy/kvasir_shard_descriptor_with_data_splitter.py#L38 This leads to duplicate shards on envoys. Ideally, the split function needs to be called once and then sharded dataset should be distributed according to the rank of the envoys.

**To Reproduce**
Run openfl-tutorials/interactive_api/PyTorch_Kvasir_Unet tutorial with 2 envoys having rank,worldsize of 1,3 and 2,3 and print the shard index for each of the envoys.

**Expected behavior**
The same data shard index should not be given to multiple envoys.

**Screenshots**
shard indices on envoy 1:
![image](https://user-images.githubusercontent.com/77758170/146615284-42c6ee01-59f6-49e0-8988-19f4a3d3258b.png)

shard indices on envoy 2:
![image](https://user-images.githubusercontent.com/77758170/146615319-603f59bb-eb7b-482f-8a6b-ad0121c10df8.png)

Index numbers like 912, 638, 651, 653 etc are present in both images.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04.6 LTS
 - Browser chrome

**Comment by itrushkin** [comment]
Data shards can intersect due to non-fixed random behavior. I have reproduced the issue and tried fixing the random seed of `RandomDataSplitter` in #288. There, data is split in a unified way meaning that if the splitter does not contain intersections, envoy shards will be unique. Please check that this PR will fix this issue.
