### ISSUE TITLE
Device parameter is not processed in TensorFlow tutorials

### ISSUE THREAD

**Issue by itrushkin** [intel/openfl#396]
**Bug description**
Interactive API Task Interface provides users with `device` parameter, but we do not use it in TensorFlow tutorials.

**To Reproduce**
Prerequisites:
Both types of CPU and CUDA devices working for your version of TensorFlow. 
You can check this condition with: `tf.config.get_physical_devices()`.
1. Open any TensorFlow Interactive API tutorial (e.g., openfl-tutorials/interactive_api/TensorFlow_MNIST)
2. Open a notebook in `workspace` folder.
3. Run all cells.
4. All tasks execution device is based on the TensorFlow device selection policy.

**Expected behavior**
Execution device is `device` from task parameters.

**Environment**
 - OS: Ubuntu 18.04
 - Python: 3.8
 - TensorFlow: 2.7
 - CUDA: 11.2

**Comment by aarushisoni** [comment]
Hi my name is Aarushi Soni . I want to contribute to this issue . Is this issue still open ? I am first time contributor . Please guide me through this process.

**Comment by szofar** [comment]
OpenFL_Team3 will attempt

**Comment by teoparvanov** [comment]
Closing as the Interactive API has been deprecated.
