### ISSUE TITLE
Support configuration of compression_pipeline by Director-Based Workflow

### ISSUE THREAD

**Issue by yanivbi** [intel/openfl#427]
I'm trying to deploy and compare the different compression pipelines supported by the project.
But, as it seems, the configuration of the compression_pipline is not supported by the director-based workflow.

**Comment by mansishr** [comment]
Hi @yanivbi , thanks for using OpenFL! By default, the director based workflow is using no compression but a small fix could alter the plan settings to pickup the compression pipeline of your choice.
