### ISSUE TITLE
Create example for tf.data with the ShardDescriptor interface

### ISSUE THREAD

**Issue by psfoley** [intel/openfl#429]

**Comment by MasterSkepticista** [comment]
Linking PR #440.
@ladi-pomsar Could you please check this `tf.data` example, if it fits your requirement?

**Comment by ladi-pomsar** [comment]
> Linking PR #440. @ladi-pomsar Could you please check this `tf.data` example, if it fits your requirement?

Hi @MasterSkepticista, looks good to me, there is just a single comment from me.
