### ISSUE TITLE
sdist distribution of openfl

### ISSUE THREAD

**Issue by sarthakpati** [intel/openfl#44]
**Is your feature request related to a problem? Please describe.**
Currently, the packaging is on wheel only, which is fine for pip but can introduce some issues when we run into mis-matched dependency versions when packaging openfl with other packages.

**Describe the solution you'd like**
Adding an `sdist` in addition to the wheel would make things much easier.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by tonyreina** [comment]
@sarthakpati Thanks. We're actually working on the conda package. It's just got to go through the right approvals, but it is coming.

**Comment by sarthakpati** [comment]
Oh cool, thanks!
