### ISSUE TITLE
This doesn't work on windows does it? 

### ISSUE THREAD

**Issue by lesliewubbel** [intel/openfl#444]
**Describe the bug**

run code on windows 11 

We are installing openFL on windows 

```
(venv) PS C:\CodeRepos\MoaniSandbox\FETS-AI\Challenge\Task_1\openfl> pip install .            Processing c:\coderepos\moanisandbox\fets-ai\challenge\task_1\openfl                            Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\CodeRepos\MoaniSandbox\FETS-AI\Challenge\Task_1\openfl\setup.py", line 79, in <module>
          long_description = f.read()
        File "C:\Users\15702\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6189: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.        
error: metadata-generation-failed


× Encountered error while generating package metadata.
╰─> See above for output.
```

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**To Reproduce**
1. cd 'C:\CodeRepos\FETS-AI\Challenge\Task_1\openfl
2.  pip install . 
3. See error

 UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6189: character maps to <undefined>
      [end of output]

**Expected behavior**

install openfl 

**possible solutions** 

Editing python file cp1252.py on my machine 

**Desktop (please complete the following information):**
WIndows 11 VScode

**Comment by lesliewubbel** [comment]
Ok so I got it to install on windows 

by changing setup.py  

from 


```
with open('README.md') as f:
    long_description = f.read()

```

to 
`
with open('README.md', encoding='utf-8') as f:
    long_description = f.read()
`

there is a better way to fix this by detecting OS then if else the open functions 

This doesn't mean openfl will work on windows as intended.

**Comment by MasterSkepticista** [comment]
@Gresliebear Thanks for finding a hidden little insect!
Your fix might work across OSes, without needing conditionals. Could you please link a PR with the fix?

**Comment by lesliewubbel** [comment]
@MasterSkepticista Sure no problem, after work in a few hours I gotta install and break it again to confirm.

**Comment by lesliewubbel** [comment]
`pip install openfl` doesn't install off the bat we have to cd into openfl and `pip install .`

![image](https://user-images.githubusercontent.com/13157730/174702542-7f38124c-96fd-49e7-84df-d13b430efd6a.png)

**Comment by lesliewubbel** [comment]
@MasterSkepticista 
https://github.com/intel/openfl/pull/445 heres the PR
