### ISSUE TITLE
Can't reconnect to federation if connection lost during data transfer from collaborator -> aggregator

### ISSUE THREAD

**Issue by psfoley** [intel/openfl#455]
A user has reported that if the network connection is lost during the SendLocalTaskResults RPC call from a collaborator to the aggregator, the collaborator cannot successfully reconnect after the outage. This task involves verifying the reported issue, making a change to the collaborator code to detect this and retry the call after the connection is reestablished.

**Comment by rahulga1** [comment]
It has been resolved with https://github.com/securefederatedai/openfl/pull/465
