### ISSUE TITLE
Sporadically Hanging Interactive API CI Test

### ISSUE THREAD

**Issue by psfoley** [intel/openfl#466]
The pytorch kvasir unet CI test has been triggering a CI timeout sporadically in the middle of training:

https://github.com/intel/openfl/runs/7525106079?check_suite_focus=true
https://github.com/intel/openfl/runs/7524916214?check_suite_focus=true
https://github.com/intel/openfl/runs/7510403486?check_suite_focus=true

![image](https://user-images.githubusercontent.com/3803396/181684392-fed9f42a-ff76-4dc1-9323-f861b73725b2.png)

**Comment by teoparvanov** [comment]
Closing this issue, as the Interactive API is being deprecated in favor of Workflow API.
