### ISSUE TITLE
[Keras_MNIST_Tutorial]: ValueError: Aggregator does not have an aggregated tensor for TensorKey

### ISSUE THREAD

**Issue by doflink** [intel/openfl#47]
Hi all, I build the openfl docker image (with current master), and I'm trying Keras Mnist tutorial with a docker container. However, currently, I get the following error:
```
final_fl_model = fx.run_experiment(collaborators,override_config={'aggregator.settings.rounds_to_train':5})
  File "/usr/local/lib/python3.8/dist-packages/openfl/native/native.py", line 297, in run_experiment
    collaborator.run_simulation()
  File "/usr/local/lib/python3.8/dist-packages/openfl/component/collaborator/collaborator.py", line 147, in run_simulation
    self.do_task(task, round_number)
  File "/usr/local/lib/python3.8/dist-packages/openfl/component/collaborator/collaborator.py", line 192, in do_task
    input_tensor_dict = self.get_numpy_dict_for_tensorkeys(
  File "/usr/local/lib/python3.8/dist-packages/openfl/component/collaborator/collaborator.py", line 214, in get_numpy_dict_for_tensorkeys
    return {k.tensor_name: self.get_data_for_tensorkey(k) for k in tensor_keys}
  File "/usr/local/lib/python3.8/dist-packages/openfl/component/collaborator/collaborator.py", line 214, in <dictcomp>
    return {k.tensor_name: self.get_data_for_tensorkey(k) for k in tensor_keys}
  File "/usr/local/lib/python3.8/dist-packages/openfl/component/collaborator/collaborator.py", line 290, in get_data_for_tensorkey
    nparray = self.get_aggregated_tensor_from_aggregator(
  File "/usr/local/lib/python3.8/dist-packages/openfl/component/collaborator/collaborator.py", line 328, in get_aggregated_tensor_from_aggregator
    tensor = self.client.get_aggregated_tensor(
  File "/usr/local/lib/python3.8/dist-packages/openfl/component/aggregator/aggregator.py", line 334, in get_aggregated_tensor
    raise ValueError("Aggregator does not have an aggregated tensor"
ValueError: Aggregator does not have an aggregated tensor for TensorKey(tensor_name='dense_3/kernel:0', origin='aggregator_plan.yaml_a379411e', round_number=0, report=False, tags=('model',))
```
**Working environment in docker container**
- Python 3.8.0
- intel-tensorflow 2.3.0

**To Reproduce**
- clone the openfl repos, and build image: ./scripts/build_base_docker_image.sh
- Run docker: _docker run -p 8888  -it --rm openfl:latest bash_
- Try out the turorial: openfl-tutorials/Federated_Keras_MNIST_Tutorial.ipynb

I think, there is an issue here: https://github.com/intel/openfl/blob/1aa2b16509a1a9a97983760a45aa1e5f133e9e30/openfl/native/native.py#L288
since the model of the first collaborator model was not initialized as the last collaborator: https://github.com/intel/openfl/blob/1aa2b16509a1a9a97983760a45aa1e5f133e9e30/openfl/native/native.py#L259
In addition, there is a sallow copy for the plan of each collaborator: https://github.com/intel/openfl/blob/develop/openfl/native/native.py#L206
Could you please help to check?
Thank you!

**Comment by psfoley** [comment]
Thanks a lot for the detailed bug report, @doflink! 

We became aware of this issue in the develop branch late last week. @itrushkin is currently working on a [fix](https://github.com/intel/openfl/pull/43), and I expect that it will be merged to the develop branch soon. For now I would recommend reverting to the latest tagged version of OpenFL ([v1.0.1](https://github.com/intel/openfl/releases/tag/v1.0.1)), which can also be installed via pypi.

**Comment by alexey-gruzdev** [comment]
@doflink @psfoley @itrushkin  I've merged the fix into develop, so now it should work.

@doflink could you, please, double-check with latest develop and let us know if you have unexpected behavior.

**Comment by doflink** [comment]
Hi @alexey-gruzdev, it works now, thanks! It seems you also fixed the download mnist dataset issue, _import mnist_ will download from *http://yann.lecun.com/exdb/mnist/* which raise error _Service Unavailable_ , import mnist from _tensorflow.keras.datasetst_ is much more stable. Thank you!
