### ISSUE TITLE
executor failed running [/bin/bash -o pipefail -c fx workspace import --archive /workspace.zip]: exit code: 1

### ISSUE THREAD

**Issue by gagandeep987123** [intel/openfl#496]
**Describe the bug**
Attemptin to run the openfl-gramine example. I am getting a error at point 4 "Build the Experiment Docker image"

**To Reproduce**
following the steps mentioned in the openfl-gramine/MANUAL. Also attaching the terminal logs for more reference.
[output.zip](https://github.com/intel/openfl/files/9453288/output.zip)

Can you please help?

**Comment by igor-davidyuk** [comment]
It is hard to tell, never saw this before.
Try this: create a clean virtual env, install openfl, and run [this script](https://github.com/intel/openfl/blob/develop/tests/github/test_graminize.sh).
See if it goes ok.

**Comment by gagandeep987123** [comment]
Just to add on while installing Openfl I am also getting this error
```  ERROR: Command errored out with exit status 1:
   command: /home/gsingh/virtuar_environments/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3f4p6l6x/flatten-json/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3f4p6l6x/flatten-json/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-d15qsliv
       cwd: /tmp/pip-install-3f4p6l6x/flatten-json/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for flatten-json
  Running setup.py clean for flatten-json
Failed to build flatten-json
ERROR: tensorboardx 2.5.1 has requirement protobuf<=3.20.1,>=3.8.0, but you'll have protobuf 4.21.5 which is incompatible.
ERROR: grpcio-tools 1.34.1 has requirement protobuf<4.0dev,>=3.5.0.post1, but you'll have protobuf 4.21.5 which is incompatible.
ERROR: tensorboard 2.10.0 has requirement protobuf<3.20,>=3.9.2, but you'll have protobuf 4.21.5 which is incompatible.
```
I had resolved this earlier by downgrading protobuf using ```pip install protobuf==3.20.1```

**Comment by gagandeep987123** [comment]
still getting the errror.
[output.zip](https://github.com/intel/openfl/files/9454113/output.zip)

**Comment by igor-davidyuk** [comment]
> still getting the errror. [output.zip](https://github.com/intel/openfl/files/9454113/output.zip)

I can not reproduce this. When I run this script image is built successfully for me, probably the reason for this is in your set up.

**Comment by gagandeep987123** [comment]
> Just to add on while installing Openfl I am also getting this error
> 
> ```
>    command: /home/gsingh/virtuar_environments/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3f4p6l6x/flatten-json/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3f4p6l6x/flatten-json/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-d15qsliv
>        cwd: /tmp/pip-install-3f4p6l6x/flatten-json/
>   Complete output (6 lines):
>   usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>      or: setup.py --help [cmd1 cmd2 ...]
>      or: setup.py --help-commands
>      or: setup.py cmd --help
>   
>   error: invalid command 'bdist_wheel'
>   ----------------------------------------
>   ERROR: Failed building wheel for flatten-json
>   Running setup.py clean for flatten-json
> Failed to build flatten-json
> ERROR: tensorboardx 2.5.1 has requirement protobuf<=3.20.1,>=3.8.0, but you'll have protobuf 4.21.5 which is incompatible.
> ERROR: grpcio-tools 1.34.1 has requirement protobuf<4.0dev,>=3.5.0.post1, but you'll have protobuf 4.21.5 which is incompatible.
> ERROR: tensorboard 2.10.0 has requirement protobuf<3.20,>=3.9.2, but you'll have protobuf 4.21.5 which is incompatible.
> ```
> 
> I had resolved this earlier by downgrading protobuf using `pip install protobuf==3.20.1`

Are you getting this error while installing openfl? I installed a lower version there

**Comment by igor-davidyuk** [comment]
> > Just to add on while installing Openfl I am also getting this error
> > ```
> >    command: /home/gsingh/virtuar_environments/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3f4p6l6x/flatten-json/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3f4p6l6x/flatten-json/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-d15qsliv
> >        cwd: /tmp/pip-install-3f4p6l6x/flatten-json/
> >   Complete output (6 lines):
> >   usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
> >      or: setup.py --help [cmd1 cmd2 ...]
> >      or: setup.py --help-commands
> >      or: setup.py cmd --help
> >   
> >   error: invalid command 'bdist_wheel'
> >   ----------------------------------------
> >   ERROR: Failed building wheel for flatten-json
> >   Running setup.py clean for flatten-json
> > Failed to build flatten-json
> > ERROR: tensorboardx 2.5.1 has requirement protobuf<=3.20.1,>=3.8.0, but you'll have protobuf 4.21.5 which is incompatible.
> > ERROR: grpcio-tools 1.34.1 has requirement protobuf<4.0dev,>=3.5.0.post1, but you'll have protobuf 4.21.5 which is incompatible.
> > ERROR: tensorboard 2.10.0 has requirement protobuf<3.20,>=3.9.2, but you'll have protobuf 4.21.5 which is incompatible.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I had resolved this earlier by downgrading protobuf using `pip install protobuf==3.20.1`
> 
> Are you getting this error while installing openfl? I installed a lower version there

No, I do not see these messages. Are you sure you run `pip install openfl` in a clean environment?

**Comment by gagandeep987123** [comment]
No, I am using it in a virtual environment

**Comment by gagandeep987123** [comment]
> > > Just to add on while installing Openfl I am also getting this error
> > > ```
> > >    command: /home/gsingh/virtuar_environments/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3f4p6l6x/flatten-json/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3f4p6l6x/flatten-json/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-d15qsliv
> > >        cwd: /tmp/pip-install-3f4p6l6x/flatten-json/
> > >   Complete output (6 lines):
> > >   usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
> > >      or: setup.py --help [cmd1 cmd2 ...]
> > >      or: setup.py --help-commands
> > >      or: setup.py cmd --help
> > >   
> > >   error: invalid command 'bdist_wheel'
> > >   ----------------------------------------
> > >   ERROR: Failed building wheel for flatten-json
> > >   Running setup.py clean for flatten-json
> > > Failed to build flatten-json
> > > ERROR: tensorboardx 2.5.1 has requirement protobuf<=3.20.1,>=3.8.0, but you'll have protobuf 4.21.5 which is incompatible.
> > > ERROR: grpcio-tools 1.34.1 has requirement protobuf<4.0dev,>=3.5.0.post1, but you'll have protobuf 4.21.5 which is incompatible.
> > > ERROR: tensorboard 2.10.0 has requirement protobuf<3.20,>=3.9.2, but you'll have protobuf 4.21.5 which is incompatible.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I had resolved this earlier by downgrading protobuf using `pip install protobuf==3.20.1`
> > 
> > 
> > Are you getting this error while installing openfl? I installed a lower version there
> 
> No, I do not see these messages. Are you sure you run `pip install openfl` in a clean environment?

The error is persistent in other machines also. I tried installing openfl in newly installed ubuntu 20 and in the virtual environment, the error is there.

**Comment by MasterSkepticista** [comment]
@gagandeep987123 It's a good idea to check the python version (3.8 recommended) and `pip` version. Any virtual environment you create, `python -m pip install -U pip` immediately after activating your environment. Install packages after `pip` has been updated.

Can you try that and see how it goes?

Although this is taken care of in the Dockerfile, from the logs it seems to be a protobuf issue. I'll check it once and let you know.

Edit: `wheel` is also quoted as a requirement. Also good to check if that is installed after `pip` is updated.

> > > > Just to add on while installing Openfl I am also getting this error
> > > > ```
> > > >    command: /home/gsingh/virtuar_environments/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3f4p6l6x/flatten-json/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3f4p6l6x/flatten-json/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-d15qsliv
> > > >        cwd: /tmp/pip-install-3f4p6l6x/flatten-json/
> > > >   Complete output (6 lines):
> > > >   usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
> > > >      or: setup.py --help [cmd1 cmd2 ...]
> > > >      or: setup.py --help-commands
> > > >      or: setup.py cmd --help
> > > >   
> > > >   error: invalid command 'bdist_wheel'
> > > >   ----------------------------------------
> > > >   ERROR: Failed building wheel for flatten-json
> > > >   Running setup.py clean for flatten-json
> > > > Failed to build flatten-json
> > > > ERROR: tensorboardx 2.5.1 has requirement protobuf<=3.20.1,>=3.8.0, but you'll have protobuf 4.21.5 which is incompatible.
> > > > ERROR: grpcio-tools 1.34.1 has requirement protobuf<4.0dev,>=3.5.0.post1, but you'll have protobuf 4.21.5 which is incompatible.
> > > > ERROR: tensorboard 2.10.0 has requirement protobuf<3.20,>=3.9.2, but you'll have protobuf 4.21.5 which is incompatible.
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > I had resolved this earlier by downgrading protobuf using `pip install protobuf==3.20.1`
> > > 
> > > 
> > > Are you getting this error while installing openfl? I installed a lower version there
> > 
> > 
> > No, I do not see these messages. Are you sure you run `pip install openfl` in a clean environment?
> 
> The error is persistent in other machines also. I tried installing openfl in newly installed ubuntu 20 and in the virtual environment, the error is there.

**Comment by igor-davidyuk** [comment]
Did you manage to resolve this issue?

**Comment by gagandeep987123** [comment]
Yes, Thank you
