### ISSUE TITLE
FedProx - PyTorch in interactive API

### ISSUE THREAD

**Issue by CasellaJr** [intel/openfl#506]
According to the documentation, in order to run FedProx in PyTorch we need to replace the optimizer with SGD-based [:class:`openfl.utilities.optimizers.torch.FedProxOptimizer`](https://github.com/intel/openfl/blob/e5b80e0a998f078bbac39efa2c5abea986df31a9/docs/supported_aggregation_algorithms.rst#id1) or Adam-based [:class:`openfl.utilities.optimizers.torch.FedProxAdam`](https://github.com/intel/openfl/blob/e5b80e0a998f078bbac39efa2c5abea986df31a9/docs/supported_aggregation_algorithms.rst#id3). Also, we should save model weights for the next round via calling .set_old_weights() method of the optimizer before the training epoch.

There are examples on how to use it in the previous Aggregator/collaborator setting, but how about the interactive API? Can you provide an example?

**Comment by bjklemme-intel** [comment]
OpenFL_Team1 is working on this
