### ISSUE TITLE
Improve resilience of director / envoy

### ISSUE THREAD

**Issue by psfoley** [intel/openfl#511]
The director / envoy infrastructure should be able to handle:
- envoy going offline and reregistering with the director
- A loss of network connectivity at different stages of execution, including:
    - Idle (Envoy registered with director, but no experiment in progress)
    - Experiment submitted to director, workspace has not been distributed to Envoy
    - Workload distributed to Envoy, experiment hasn't started
    - Experiment started

**Comment by aleksandr-mokrov** [comment]
These scenarios are covered by https://github.com/intel/openfl/pull/623 and https://github.com/intel/openfl/pull/624. In addition some problems with restarting services (director or envoy) are fixed.
