### ISSUE TITLE
Documentation: Recommended hardware for workloads

### ISSUE THREAD

**Issue by psfoley** [intel/openfl#512]
Customers have expressed a desire for a minimum acceptable hardware configuration for various workloads.

This task involves:
- Starting with 3 OpenFL tutorials (pytorch, tensorflow, jax), Profile how long it takes to run them and make a recommendation for the minimum hardware that should be used (i.e. high core CPU, GPU, memory, etc.). This list should be expanded over time (not as part of this task)
- Create a new page in the OpenFL documentation that includes a table of the available tutorials that includes this information

**Comment by vivektalwar13071999** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by MasterSkepticista** [comment]
Closing because this issue is stale. We can reopen this as priorities change.
