### ISSUE TITLE
Interactive API tutorial in Google Colab fails

### ISSUE THREAD

**Issue by igor-davidyuk** [intel/openfl#515]
It goes OK until I call `start_experiment` RPC, which fails silently. After that, the `stream_metrics` RPC just hangs forever.

**Comment by igor-davidyuk** [comment]
Investigation revealed the following:
- Local Jupyter Lab runs the example without any issue.
- Google Colab environment prevents changing the logging level for some reason. OpenFL logging settings do not work in Colab, making debugging harder: `INFO` messages are not displayed. Setting logging basicConfig explicitly does not work either.
- OpenFL actors running in the background also experience problems with logging. Director, for instance, fails to write any log at all, changing log levels does not help.
- Nevertheless, Director can obtain and unpack an experiment, but it is hard to say if it actually runs any round.
- Status is still the same: even with increased logging level, `stream_metrics` does not print metrics info in any reasonable time, which makes Colab example nonfunctioning, as for now.

**Comment by psfoley** [comment]
@igor-davidyuk This was something we also encountered creating the examples for the MICCAI tutorial. The logging level in Google Colab is set to `WARNING` by default. This is not a fix, but for debugging purposes you can set the logger root level to `INFO` in `cli.py` and you should at least get some meaningful output that way: https://github.com/intel/openfl/blob/45581202f2b479812ff102d75da26a830d847125/openfl/interface/cli.py#L45

**Comment by igor-davidyuk** [comment]
I couldn't google this solution for changing the log level 😂, thank you!
It worked for the Python API logs, but the Director remained silent

**Comment by igor-davidyuk** [comment]
That is so strange, I am sure I left a comment here but now it is gone. Anyway, the update:
1. I tried to change the logging level in several places inside Director and Aggregator actors code, had no effect, the director still writes no logs.
2. I tested the original branch in Colab that worked back then, and the experiment also got stuck in the same place, so some change in the Colab environment probably causes this.

Need to detect and mitigate this new issue.

**Comment by igor-davidyuk** [comment]
Next update: I tried to run the Miccai tutorial and that one works.
I believe [this fix](https://github.com/intel/openfl/blob/6637146ca08e11ff553bca27786acc684faf4f1c/openfl/component/envoy/envoy.py#L89) allows the example to run correctly in Colab, it prevents installing requirements for the experiment at the Envoy side.
It is hard to determine the exact problem as the Envoys and Director still do not write logs.
We can not merge the fix as it is not generally applicable, in my opinion, a good decision would be to include the option of installing dependencies to Envoy / Director configs.

It seems like @MasterSkepticista was the first who discovered the issue and found a workaround. @MasterSkepticista could you create an issue and describe your experience and your solution? (It would save me a few weeks if you did right away 😂)

**Comment by MasterSkepticista** [comment]
@igor-davidyuk You seem to have created #536 recently to address the requirements issue. 
As for logging, per my understanding, Colab sets an internal log-level (probably `WARN` for all scripts). This is a fairly recent change. Logging worked perfectly, weeks before the actual MICCAI tutorial. 

Setting `logging.root.level = 20` works because it only applies that to the current runtime. Director/Envoy still spawn their independent processes, which do not have the `logging.root.level` modified. 

Nonetheless, I was able to get the Director/Envoy print the logs on `stdout` with an additional cell fix (if my memory serves right)

[Notebook Link](https://github.com/intel/fl-tutorial/blob/gh-pages/tutorial_notebooks/Tutorial_1_Medmnist_2D.ipynb)
![image](https://user-images.githubusercontent.com/30374293/196856054-4f14ae9e-27e9-4f76-8dff-dab1cf9b72e5.png)

**Comment by igor-davidyuk** [comment]
> @igor-davidyuk You seem to have created #536 recently to address the requirements issue. As for logging, per my understanding, Colab sets an internal log-level (probably `WARN` for all scripts). This is a fairly recent change. Logging worked perfectly, weeks before the actual MICCAI tutorial.
> 
> Setting `logging.root.level = 20` works because it only applies that to the current runtime. Director/Envoy still spawn their independent processes, which do not have the `logging.root.level` modified.
> 
> Nonetheless, I was able to get the Director/Envoy print the logs on `stdout` with an additional cell fix (if my memory serves right)
> 
> [Notebook Link](https://github.com/intel/fl-tutorial/blob/gh-pages/tutorial_notebooks/Tutorial_1_Medmnist_2D.ipynb) ![image](https://user-images.githubusercontent.com/30374293/196856054-4f14ae9e-27e9-4f76-8dff-dab1cf9b72e5.png)

Thank you for the clarification, Google certainly made some changes to Colab runtime so logging now is problematical.
Nevertheless, could you still create a GitHub issue and describe shortly facing the problem so we can close it in PR?
