### ISSUE TITLE
Documentation needed - how to integrate a new code into OpenFL

### ISSUE THREAD

**Issue by mkirnaso** [intel/openfl#521]
There is no clear manual on how to integrate a new ML code into OpenFL. Until now I have been trying to modify existing example such as PyTorch_MNIST and put my code in it instead, but this is not the "correct" way to do it. On the other hand there is no concrete documentation on how to do it properly.

**Comment by mansishr** [comment]
Hi @mkirnaso, welcome to OpenFL! I understand that you would like to integrate your ML model/data into OpenFL. The easiest way is to utilize our [tutorials](https://github.com/intel/openfl/tree/develop/openfl-tutorials/interactive_api) that showcase python interactive API/Director-Envoy based flow or [workspace templates](https://github.com/intel/openfl/tree/develop/openfl-workspace) that utilize OpenFL CLI flow. Most of the tutorials have a README and if you'd like to understand the flow, [this ](https://openfl.readthedocs.io/en/latest/running_the_federation.html#director-based-workflow) might be helpful. To use the workspace templates, here is the [documentation](https://openfl.readthedocs.io/en/latest/running_the_federation.html#aggregator-based-workflow).

Let me know if this helps you out. We are in the process of refining our documentation, so stay tuned!

**Comment by BenjaminAcar** [comment]
Hey, why is it not working? As an alternative you could just replace the code init process with loading in a .h5 file (or whatever it is for pytorch, I am using only tensorflow) and then compile the model to make it work.

I did it for tensorflow and it was pretty straightforward.

**Comment by teoparvanov** [comment]
We have introduced a number of TaskRunner API documentation improvements in OpenFL 1.6, including:
- [A revised quick-start tutorial with Task Runner API](https://openfl.readthedocs.io/en/latest/get_started/quickstart.html#quick-start)
- [Enhanced documentation for composing the FL plan](https://openfl.readthedocs.io/en/latest/about/features_index/taskrunner.html#federated-learning-plan-fl-plan-settings)
- You could also refer to a recent [blog post](https://medium.com/openfl/from-centralized-machine-learning-to-federated-learning-with-openfl-b3e61da52432) that walks through the entire process of transforming a centralized ML model into a FL experiment.

From a longer term perspective, we invite everyone to start using the Workflow API which is going to become the main method for building OpenFL federations in the upcoming releases:
- [Workflow API Overview](https://openfl.readthedocs.io/en/latest/about/features_index/workflowinterface.html)
- [101 Jupyter Notebook](https://github.com/securefederatedai/openfl/blob/develop/openfl-tutorials/experimental/101_MNIST.ipynb).

Finally, don't hesitate to join us on [Slack](https://join.slack.com/t/openfl/shared_invite/zt-ovzbohvn-T5fApk05~YS_iZhjJ5yaTw) to get additional help onboarding with OpenFL.
