### ISSUE TITLE
Setup fails with Python>3.8

### ISSUE THREAD

**Issue by DL8** [intel/openfl#522]
**Describe the bug**
OpenFL installation fails with Python >3.8. I tried with Python 3.10 on a Debian 11-based image

**To Reproduce**
1. Clone repository
2. Go to repository directory
3. Try to install:
```pip install .```

**Expected behavior**
OpenFL installs

**Screenshots**
![image](https://user-images.githubusercontent.com/3604408/193448338-e116aaf9-9f08-433f-85db-c108bc0d3e80.png)

**Comment by sun1lach** [comment]
@DL8 
This looks familiar.

I would suggest below steps
1. Use virtual environment.
2. remove existing ` setuptools` using pip and install this specific version `pip install setuptools==44.0.0`.

[Optional] If the base distutil package is corrupted/outdated, try reinstall using `sudo apt-get install python3-distutils`

**Comment by psfoley** [comment]
@DL8 Thanks for reporting this. That particular error was due to a version of grpcio that is unsupported in python 3.10 that we had pinned. I have a PR open now that aims to adds official support for more [recent python versions](https://github.com/intel/openfl/pull/532)

**Comment by psfoley** [comment]
Fixed with https://github.com/intel/openfl/pull/532
