### ISSUE TITLE
Kvasir example in Gramine fails

### ISSUE THREAD

**Issue by igor-davidyuk** [intel/openfl#575]
Training fails with the following message: `DefaultCPUAllocator: can't allocate memory: you tried to allocate 225738752 bytes. Error code 12 (Cannot allocate memory)` on the collaborator side.

[Logs attached](https://github.com/intel/openfl/files/9951006/gramine-kvasir.log)

**Comment by bjklemme-intel** [comment]
Could provide a link to the example?

**Comment by bjklemme-intel** [comment]
"OpenFL_Team1 is working on this"

**Comment by teoparvanov** [comment]
The graminized Kvasir example has been removed as part of a broader refactoring of workspace graminization in OpenFL.
