### ISSUE TITLE
Setup of 'fx' failed on conda 4.6.11, worked on 4.10.1

### ISSUE THREAD

**Issue by msheller** [intel/openfl#64]
**Describe the bug**
When following the setup instructions using conda 4.6, the resulting conda environment failed to install openfl in the environment. While not an openfl bug, we may want to determine how to make these instructions work on older conda versions.
NOTE: I am using the 'develop' branch.

**To Reproduce**
1. Install conda 4.6.11 on Ubuntu 18.04
2. Follow the initial setup instructions for openfl
3. Note that openfl has not been installed in the conda environment, thus 'fx' doesn't work. "which pip" and "which python" also don't point to the environment pip/python, either.
4. Deactivate and remove the conda environment you created as part of openfl setup
5. Update conda to 4.10.1
6. Follow openfl setup instructions
7. fx now works and is installed in the conda environment

**Comment by tonyreina** [comment]
just to confirm. Did you specify `pip` and `python` when you created the conda environment?

`conda create -n env_name pip python=3.6`

**Comment by mansishr** [comment]
With conda 4.6.11 on Ubuntu 18.04, after creating the the conda environment (conda create -n env_name pip python=3.6) and installing a few dependent packages, 'fx' got setup successfully. Recommended to still upgrade to latest conda version.
