### ISSUE TITLE
Error in Tensorflow_MNIST Tutorial numpy version 1.24.1

### ISSUE THREAD

**Issue by ishant162** [intel/openfl#686]
**Describe the bug**
While running Director Workflow Tensorflow_MNIST Tutorial on WSL (Ubuntu 20.04) it gives an error
Experiment "mnist_experiment" failed with error: module 'numpy' has no attribute 'int'.

**To Reproduce**
1. python -m venv venv
2. source venv/bin/activate
3. python -m pip install -U pip setuptools wheel
4. git clone https://github.com/intel/openfl.git
5. cd openfl/
pip install .
6. cd openfl/openfl-tutorials/interactive_api/Tensorflow_MNIST
7. cd director
./start_director.sh
8. cd envoy
./start_envoy.sh env_one envoy_config_one.yaml
9. cd workspace
code .
10. Run the experiment in Visual Studio code Remotely

**Expected behavior**
Experiment should run successfully without any error

**Error logs**
Error message while running the experiment
INFO     🧿 Created an Aggregator Server for mnist_experiment experiment.                                                           experiment.py:131
           INFO     Building 🡆  Object CloudpickleSerializer from openfl.plugins.interface_serializer.cloudpickle_serializer Module.                  plan.py:171
           INFO     Building 🡆  Object KCPipeline from openfl.pipelines Module.                                                                       plan.py:171
           INFO     Building 🡆  Object CutoffTimeBasedStragglerHandling from openfl.component.straggler_handling_functions Module.                    plan.py:171
           INFO     Building 🡆  Object Aggregator from openfl.component Module.                                                                       plan.py:171
           ERROR    Experiment "mnist_experiment" failed with error: module 'numpy' has no attribute 'int'.                                     experiment.py:94
                    Traceback (most recent call last):
                      File "/home/ithakarx/newEnv/lib/python3.8/site-packages/openfl/component/director/experiment.py", line 76, in start
                        aggregator_grpc_server = self._create_aggregator_grpc_server(
                      File "/home/ithakarx/newEnv/lib/python3.8/site-packages/openfl/component/director/experiment.py", line 132, in
                    _create_aggregator_grpc_server
                        aggregator_grpc_server = plan.interactive_api_get_server(
                      File "/home/ithakarx/newEnv/lib/python3.8/site-packages/openfl/federated/plan/plan.py", line 559, in
                    interactive_api_get_server
                        server_args['aggregator'] = self.get_aggregator(tensor_dict)
                      File "/home/ithakarx/newEnv/lib/python3.8/site-packages/openfl/federated/plan/plan.py", line 338, in get_aggregator
                        self.aggregator_ = Plan.build(**defaults, initial_tensor_dict=tensor_dict)
                      File "/home/ithakarx/newEnv/lib/python3.8/site-packages/openfl/federated/plan/plan.py", line 182, in build
                        instance = getattr(module, class_name)(**settings)
                      File "/home/ithakarx/newEnv/lib/python3.8/site-packages/openfl/component/aggregator/aggregator.py", line 114, in __init__
                        self.model = utils.construct_model_proto(
                      File "/home/ithakarx/newEnv/lib/python3.8/site-packages/openfl/protocols/utils.py", line 137, in construct_model_proto
                        bytes_data, transformer_metadata = tensor_pipe.forward(data=nparray)
                      File "/home/ithakarx/newEnv/lib/python3.8/site-packages/openfl/pipelines/pipeline.py", line 134, in forward
                        data, metadata = transformer.forward(data=data, **kwargs)
                      File "/home/ithakarx/newEnv/lib/python3.8/site-packages/openfl/pipelines/kc_pipeline.py", line 52, in forward
                        int_array, int2float_map = self._float_to_int(quant_array)
                      File "/home/ithakarx/newEnv/lib/python3.8/site-packages/openfl/pipelines/kc_pipeline.py", line 91, in _float_to_int
                        int_array = np.zeros(flatten_array.shape, dtype=np.int)
                      File "/home/ithakarx/newEnv/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
                        raise AttributeError("module {!r} has no attribute "
                    AttributeError: module 'numpy' has no attribute 'int'

**Desktop (please complete the following information):**
- OS: Windows 11 (WSL2 Ubuntu 20.04)
- Python 3.8.15

**Additional context**
All the Requirements and Packages which are installed by default

Building wheels for collected packages: openfl
  Building wheel for openfl (setup.py) ... done
  Created wheel for openfl: filename=openfl-1.4-py3-none-any.whl size=4509686 sha256=8e3daff1638d5c6bb04aa2edc5d90555230d4537ca7277c289b4c51176690641
  Stored in directory: /tmp/pip-ephem-wheel-cache-715cmxmu/wheels/fc/db/71/bf72d95009ad0434707fc5ba52b00d079e8e9bc867da4dc724
Successfully built openfl
Installing collected packages: webencodings, wcwidth, tensorboard-plugin-wit, send2trash, pytz, pyasn1, pure-eval, ptyprocess, pickleshare, mistune, json5, ipython-genutils, fastjsonschema, executing, commonmark, charset-normalizer, backcall, zipp, websocket-client, webcolors, urllib3, uri-template, typing-extensions, traitlets, tqdm, tornado, tomli, tinycss2, threadpoolctl, tensorboard-data-server, soupsieve, sniffio, six, rsa, rfc3986-validator, pyzmq, PyYAML, python-json-logger, pyrsistent, pygments, pycparser, pyasn1-modules, psutil, protobuf, prompt-toolkit, prometheus-client, platformdirs, pkgutil-resolve-name, pexpect, parso, pandocfilters, packaging, oauthlib, numpy, nest-asyncio, MarkupSafe, jupyterlab-pygments, jsonpointer, joblib, idna, fqdn, entrypoints, dynaconf, defusedxml, decorator, debugpy, cloudpickle, Click, certifi, cachetools, babel, attrs, absl-py, werkzeug, terminado, tensorboardX, scipy, rich, rfc3339-validator, requests, python-dateutil, matplotlib-inline, jupyter-core, jinja2, jedi, importlib-resources, importlib-metadata, grpcio, google-auth, flatten_json, comm, cffi, bleach, beautifulsoup4, asttokens, anyio, stack-data, scikit-learn, requests-oauthlib, pandas, markdown, jupyter-server-terminals, jupyter-client, jsonschema, docker, cryptography, arrow, argon2-cffi-bindings, nbformat, isoduration, ipython, google-auth-oauthlib, argon2-cffi, tensorboard, nbclient, ipykernel, nbconvert, jupyter-events, jupyter-server, notebook-shim, jupyterlab-server, nbclassic, notebook, jupyterlab, openfl
Successfully installed Click-8.0.1 MarkupSafe-2.1.1 PyYAML-6.0 absl-py-1.4.0 anyio-3.6.2 argon2-cffi-21.3.0 argon2-cffi-bindings-21.2.0 arrow-1.2.3 asttokens-2.2.1 attrs-22.2.0 babel-2.11.0 backcall-0.2.0 beautifulsoup4-4.11.1 bleach-5.0.1 cachetools-5.2.1 certifi-2022.12.7 cffi-1.15.1 charset-normalizer-3.0.1 cloudpickle-2.2.0 comm-0.1.2 commonmark-0.9.1 cryptography-39.0.0 debugpy-1.6.5 decorator-5.1.1 defusedxml-0.7.1 docker-6.0.1 dynaconf-3.1.7 entrypoints-0.4 executing-1.2.0 fastjsonschema-2.16.2 flatten_json-0.1.13 fqdn-1.5.1 google-auth-2.16.0 google-auth-oauthlib-0.4.6 grpcio-1.48.2 idna-3.4 importlib-metadata-6.0.0 importlib-resources-5.10.2 ipykernel-6.20.1 ipython-8.8.0 ipython-genutils-0.2.0 isoduration-20.11.0 jedi-0.18.2 jinja2-3.1.2 joblib-1.2.0 json5-0.9.11 jsonpointer-2.3 jsonschema-4.17.3 jupyter-client-7.4.9 jupyter-core-5.1.3 jupyter-events-0.6.3 jupyter-server-2.1.0 jupyter-server-terminals-0.4.4 jupyterlab-3.5.2 jupyterlab-pygments-0.2.2 jupyterlab-server-2.18.0 markdown-3.4.1 matplotlib-inline-0.1.6 mistune-2.0.4 nbclassic-0.4.8 nbclient-0.7.2 nbconvert-7.2.7 nbformat-5.7.3 nest-asyncio-1.5.6 notebook-6.5.2 notebook-shim-0.2.2 numpy-1.24.1 oauthlib-3.2.2 openfl-1.4 packaging-23.0 pandas-1.5.2 pandocfilters-1.5.0 parso-0.8.3 pexpect-4.8.0 pickleshare-0.7.5 pkgutil-resolve-name-1.3.10 platformdirs-2.6.2 prometheus-client-0.15.0 prompt-toolkit-3.0.36 protobuf-3.19.6 psutil-5.9.4 ptyprocess-0.7.0 pure-eval-0.2.2 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycparser-2.21 pygments-2.14.0 pyrsistent-0.19.3 python-dateutil-2.8.2 python-json-logger-2.0.4 pytz-2022.7 pyzmq-25.0.0 requests-2.28.2 requests-oauthlib-1.3.1 rfc3339-validator-0.1.4 rfc3986-validator-0.1.1 rich-13.0.1 rsa-4.9 scikit-learn-1.2.0 scipy-1.10.0 send2trash-1.8.0 six-1.16.0 sniffio-1.3.0 soupsieve-2.3.2.post1 stack-data-0.6.2 tensorboard-2.11.1 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.1 tensorboardX-2.5.1 terminado-0.17.1 threadpoolctl-3.1.0 tinycss2-1.2.1 tomli-2.0.1 tornado-6.2 tqdm-4.64.1 traitlets-5.8.1 typing-extensions-4.4.0 uri-template-1.2.0 urllib3-1.26.14 wcwidth-0.2.5 webcolors-1.12 webencodings-0.5.1 websocket-client-1.4.2 werkzeug-2.2.2 zipp-3.11.0
(newEnv) (base) ithakarx@ithakarx-mobl:~/testDir/openfl$

**Comment by aleksandr-mokrov** [comment]
numpy version is not pinned in OpenFL and, unfortunately, starting from numpy 1.24.x backward compatibility is broken. I checked versions 1.22.2 and 1.23.5, it works. As temporary workaround, you can manually install numpy==1.23.5 or earlier version in your virtual environment.

**Comment by ishant162** [comment]
Hi @aleksandr-mokrov 

Thanks for your feedback. My understanding is as follows:
- As mentioned since numpy version is not pinned, by default latest numpy version is installed (refer log snippets above)
- Numpy versions 1.22.2 and 1.23.5 raises a warning when we use **dtype=np.int** due to which the workaround suggested works
- Numpy versions following 1.24.0 will give an error and tutorial fails

Summary: Issue seems very similar to PR #683. I have created PR #694 to handle this error. Request to please review if it is suitable

**Comment by ishant162** [comment]
Closed with #694
