### ISSUE TITLE
Docker image - enhance description on hub.docker.com

### ISSUE THREAD

**Issue by rstoki** [intel/openfl#70]
**Is your feature request related to a problem? Please describe.**
Currently, there is an ambiguity of image name "openfl" in the Docker Hub, since there is product called "Open Flash Library". 
The "docker pull openfl" (as stated in the documentation) will point to the `openfl/openfl`, which is the other product: 
[https://hub.docker.com/r/openfl/openfl](https://hub.docker.com/r/openfl/openfl)

Finding the correct docker image [intel/openfl](https://hub.docker.com/r/intel/openfl) does not provide very confidence, since there is no associated description, 

**Describe the solution you'd like**
1) Please add some more informative description to the Docker-Hub page of the project: 
   https://hub.docker.com/r/intel/openfl
2) please update the [documentation instruction](https://openfl.readthedocs.io/en/latest/install.docker.html) reading:
`docker pull intel/openfl`

**Comment by alexey-gruzdev** [comment]
@rstoki This DockerHub image corresponds to different repository which is not connected to OpenFL (however it has the same naming). Currently, we are in the process of publishing our Docker image on the DockerHub. So, I will update this issue once it will be done.

**Comment by rstoki** [comment]
The image `intel/openfl` does not correspond to this OpenFL repository?

**Comment by alexey-gruzdev** [comment]
@rstoki I mean `openfl/openfl` image not corresponds to this OpenFL repo.

**Comment by alexey-gruzdev** [comment]
@rstoki we are glad to inform that docker image was released and you could use this one along with `PyPI` installation.
```
>> docker pull intel/openfl
Using default tag: latest
latest: Pulling from intel/openfl
ec9564969814: Pull complete
Digest: sha256:4b822d7d438563df3c726f5fafdd929cd206e1e261d1fa75fa5f1e4e0d4b119d
Status: Downloaded newer image for intel/openfl:latest
docker.io/intel/openfl:latest

```
Description here is also updated: https://hub.docker.com/r/intel/openfl
