### ISSUE TITLE
Docker image - Manifest not found

### ISSUE THREAD

**Issue by rstoki** [intel/openfl#71]
**Describe the bug**
Trying to install docker image gives the following error: 
`$ sudo docker pull intel/openfl` 
`Using default tag: latest`
`Error response from daemon: manifest for intel/openfl:latest not found: manifest unknown: manifest unknown`

**To Reproduce**
1. have a "clean" linux machine with docker installed
2. `sudo docker pull intel/openfl`
3. See error 

**Expected behavior**
The intel/openfl image will be successfully installed

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04
 - Docker version 20.10.6, build 370c289

**Comment by psfoley** [comment]
Thank you @rstoki for submitting this issue! The `intel/openfl` docker image should be posted to DockerHub within the next week or two. As a temporary workaround, you can build the image yourself by cloning the repo and running `./scripts/build_base_docker_image.sh` from the base directory.

**Comment by alexey-gruzdev** [comment]
@rstoki since Docker image currently available I believe we could close this issue.
