### ISSUE TITLE
Workflow Interface: AST parsing error can arise in jupyter notebooks

### ISSUE THREAD

**Issue by psfoley** [intel/openfl#724]
When using the new experimental workflow interface in a jupyter notebook, an error produced at any point during execution may lead to an AST parsing error when calling `flow.run()`. The error is thrown by metaflow's DAG generation code:

![image](https://user-images.githubusercontent.com/3803396/217349091-2938d000-ebc3-44dd-88f6-24cfe3f2629c.png)

Because the error is generated at the metaflow level, I think the DAG UI genertion code should likely be disabled by default, and we should provide an argument to enable it instead.

**Comment by KeertiX** [comment]
STEPS TO REPRODUCE :
	- Add syntax error in any cell and run. Fix the error and rerun the cell. FlFlow.run() throws an error which is unexpected 

ANALYSIS: 
	- Issue seems to be caused in openfl/experimental/utilities/metaflow_utils.py: _create_nodes() function
	- Inside _create_nodes() function, the getsource(module) is not able to fetch the latest source code from the Jupyter 
	   notebook. It seems to fetch the source code when the iPython kernel was started / restarted and if this source code 
           has an error this will result in parsing error 

ADDITIONAL INFORMATION: 
      - Issue is not observed if the IPython kernel is restarted after fixing the error

PROPOSALs: 
    Step-1: Refactor FlowGraph from MetaflowInterface to InspectFlow
	         - After this change user will not encounter issue with Graph generation during flflow.run(). Issue will be 
	            encountered only when the Graph is generated via InspectFlow() interface

    Step-2:  Fetch only Source code for the Flow
		 - Current code is fetching the source for the entire module in which flow is defined (in this case jupyter notebook). 
		    However source code   for  the Flow is enough for graph generation
		- This may also obviate the need to reload the Flow class

NEXT STEPS:
              -  Working on changes described in Step-1 and Step-2. PR to be raised once basic sanity is done

**Comment by tanwarsh** [comment]
This issue is already fixed as a part of PR [910](https://github.com/securefederatedai/openfl/pull/910)
Confirmed by trying to reproduce this issue.

Added syntax error.
<img width="1220" alt="Screenshot 2024-10-17 at 10 08 42 AM" src="https://github.com/user-attachments/assets/7785a881-1304-420f-a678-6190cd61f963">

Rerun after fixing the error:
<img width="1209" alt="Screenshot 2024-10-17 at 10 14 06 AM" src="https://github.com/user-attachments/assets/15aeaf20-f880-4e29-b185-85b982ad21df">
