### ISSUE TITLE
Bring OpenFL to 90%+ Code Coverage

### ISSUE THREAD

**Issue by psfoley** [intel/openfl#752]
OpenFL has [57-58%](https://github.com/intel/openfl/actions/runs/4233228613/jobs/7353913961) code coverage today. This task involves adding new [unit tests](https://github.com/intel/openfl/tree/develop/tests/openfl) to get above 90% project test coverage

**Comment by LeiChenIntel** [comment]
OpenFL_Team4 is working on this
