### ISSUE TITLE
The review experiment feature has an infinite loop side effect 

### ISSUE THREAD

**Issue by igor-davidyuk** [intel/openfl#759]
**Describe the bug**
Envoy's collaborator may infinitely try reconnecting to the aggregator, while it had already shut down by Director service.

**To Reproduce**
1. Enable the `review experiment` feature in Director and Envoy configs
2. Create a federation with a Director and two Envoys
3. Submit an experiment to the Director, and approve the experiment in Director's console
4. Reject the experiment in the first Envoy's console. The aggregator for the experiment will shut down.
5. Approve the experiment in the second Envoy's console. It will start a collaborator trying to connect to the Aggregator endlessly.

**Comment by teoparvanov** [comment]
Closing this issue, as the Interactive API is being deprecated in favor of Workflow API.
