### ISSUE TITLE
FX CLI: Separate user creation from TLS certificate request generation

### ISSUE THREAD

**Issue by psfoley** [intel/openfl#768]
## Background
Today in the `fx` cli, there is a combined step that create a user for an experiment and also generates a certificate signing request for them. While the use of mutual TLS is the default in OpenFL, we should not impose it on users for all environments (for example, there can be issues defining a FQDN on internal/personal infrastructure).  

## Task
1. Split `fx collaborator generate-cert-request` into two commands:
    - `fx collaborator create -n {NAME} -d {DATA_PATH: optional}` : 
    - `fx collaborator generate-cert-request -n {NAME}`
 
## TODO items for maintainers
1. Clarify how users should be added to the `plan/cols.yaml` file when not using TLS

**Comment by wangleflex** [comment]
OpenFL_Team2 Working on this issue.

**Comment by bjklemme-intel** [comment]
OpenFL_Team1 is working on this
