### ISSUE TITLE
Add PyTorch linear regression example

### ISSUE THREAD

**Issue by sprash** [intel/openfl#797]
Add a PyTorch tutorial of linear regression.
For reference, see linear regression examples with Numpy and JAX. 
https://github.com/securefederatedai/openfl/tree/develop/openfl-tutorials/interactive_api/numpy_linear_regression
https://github.com/securefederatedai/openfl/tree/develop/openfl-tutorials/interactive_api/jax_linear_regression

**Comment by danhe1** [comment]
openfl team 2 is working on this issue.
