### ISSUE TITLE
Add a Scikit-learn example of linear regression.

### ISSUE THREAD

**Issue by sprash** [intel/openfl#798]
Add a Scikit-learn tutorial of linear regression. 
For reference, see linear regression tutorials with Numpy and JAX:
https://github.com/securefederatedai/openfl/tree/develop/openfl-tutorials/interactive_api/numpy_linear_regression
https://github.com/securefederatedai/openfl/tree/develop/openfl-tutorials/interactive_api/jax_linear_regression

**Comment by bjklemme-intel** [comment]
OpenFL_Team1 is working on this

**Comment by bjklemme-intel** [comment]
Can we still use numpy for the data generation or do we have to have everything (even outside the model) converted to Scikit-learn?
