### ISSUE TITLE
Change OpenFL documentation font to improve accessibility

### ISSUE THREAD

**Issue by SprashAI** [intel/openfl#799]
We want to make OpenFL documentation accessible to low-vision developers.  Intel has created Intel One Mono font. A monospace typeface designed with input from a team of low-vision and legally blind developers for optimized legibility. 
Update OpenFL documentation to use Intel One Mono font:
Documentation: https://openfl.readthedocs.io/en/latest/index.html
Font: https://github.com/intel/intel-one-mono

Background on the Intel Mono font. The font is easier to read, and available for free, with an open-source font license. We designed the Intel One Mono typeface for maximum legibility to address developers' fatigue and eyestrain and reduce coding errors. 
Key design characteristics that increase legibility:

- Character differentiation: letters and coding glyphs designed to increase the differentiation between "like" characters. For example, the lowercase ‘e’ and cap ‘G’, where both shapes are prone to be confused with others and need extra clarification. These treatments reduce the need to skip back and confirm what’s been read.

- Differentiated upper- and lowercase height: unlike most monospace fonts that have increased x-heights, our research showed that bigger differences between capital and lowercase letters, along with longer ascenders and descenders could help create more radical "word-shapes".

**Comment by e-mny** [comment]
Hi! Is this available for me to take on?

**Comment by wangleflex** [comment]
openfl team 2 is working on this issue
