### ISSUE TITLE
Slack Invite

### ISSUE THREAD

**Issue by siddhartha18101** [intel/openfl#83]
Hello!

I hope whoever reading it is safe and doing great. It seems like people outside intel are unable to join the slack, can anyone give invite for people outside slack

**Comment by alexey-gruzdev** [comment]
@siddhartha18101 Hi! Thanks for the interest. Could you try to use this link - https://join.slack.com/t/openfl/shared_invite/zt-ovzbohvn-T5fApk05~YS_iZhjJ5yaTw for accessing? It should work. If not, could you attach a screenshot, what you are seeing when trying to join the slack.

**Comment by siddhartha18101** [comment]
Thanks for the Response. The link is working
