### ISSUE TITLE
Aggregator not reponding to collaborator: Status UNAVAILABLE

### ISSUE THREAD

**Issue by vinaBira** [intel/openfl#830]
### Discussed in https://github.com/securefederatedai/openfl/discussions/829

<div type='discussions-op-text'>

<sup>Originally posted by **vinaBira** May 17, 2023</sup>
I tried Aggregator and collaborator model from https://openfl.readthedocs.io/en/latest/running_the_federation.html#aggregator-based-workflow as it is on one GPU machine as aggrgator and Edge devices Jetson nanos as collaborator.
All of the devices have as per requirements like python3 version mentioned in the openfl documentation.

I started with basic torch_cnn_model
But,
My collaborator got stuck with :StatusCode.UNAVAILABLE     
Attempting to connect to aggregator at [host name]:[port]
Task is not assigned from server node.

Does implementation supported for Jetson nanos?
I tried opening ports with UFW and proxy sever setup as well from similar few discussion pointing the same error.
New firewall rule made still not working,
Could you please guide me in correct direction to complete the setup?</div>

**Comment by psfoley** [comment]
Hi @vinaBira! Thanks for the question. Jetson Nano is not something we have tested internally, but I would expect OpenFL should run on it. `StatusCode.UNAVAILABLE` can have multiple causes. Considering you have a multinode setup, the first suggestion I have is to verify that the FQDN is set in `plan/plan.yaml` (This should match the command output of `hostname --fqdn` on the aggregator node). Using that FQDN address, verify you can ping the aggregator from your jetson nano devices (`ping <HOSTNAME_FQDN>`). If that works, I would recommend starting the aggregator (`fx aggregator start`), and then from your jetson nano collaborator nodes run `telnet <AGGREGATOR_FQDN> <PORT_FROM_PLAN>`. If you're not able to establish a connection, there's probably a firewall issue. If you are not able to connect, please follow up and we will get you unblocked!

**Comment by vinaBira** [comment]
@psfoley My collaborator was not pinging aggregator with hostname.
I made changes accordingly, now it is working!
Thank you so much saved my day!
