### ISSUE TITLE
OpenFL name clash, is it possible to rename your project in the interest of opensource.

### ISSUE THREAD

**Issue by nanjizal** [intel/openfl#837]
OpenFL is a well used opensouce project since 2013 ( originally nekonme on googlecode from 2006 ). 
https://www.openfl.org/
  
Your project seems only a few years old, it's name clash seems misfortunate since your also using the #OpenFL hashtag on twitter.
https://github.com/securefederatedai/openfl/commit/4c898e516137c3552bb198b9bcb12d4c8e482a0e

It is not ideal for large corporations / University's to reuse another opensource projects name, it is like a shadow variable and overshadows the original project confusingly, especially as Haxe OpenFL is a toolkit, with some minor popularity within indie gamers ( lots of youngsters are using hxFlixel with OpenFL for Friday night funkin rythm game mods ).

I suggest that it would be less confusing if you renamed your project, or atleast referenced the OpenFL haxe game engine in the header info at the top of your readme.

Many thanks a concerned Haxe language user.

**Comment by Dimensionscape** [comment]
Indeed, as a core maintainer of OpenFL, this is concerning. There is a conflicting legal interest here as both projects fall into the domain of software and can easily be confused for one another. I dare say this is a bit infringing.

**Comment by dimensionscape** [comment]
Indeed, as a core maintainer of OpenFL, this is concerning. There is a conflicting interest here as both projects fall into the domain of software and can easily be confused for one another...

**Comment by psfoley** [comment]
@nanjizal and @Dimensionscape - Thank you for raising this concern. I'm a maintainer for the Open Federated Learning (OpenFL) project, and wanted to let you know that my team has been discussing this internally. Our developer communities have no overlap - ours is a AI/ML framework so there should be no confusion, however your proposal to include a link at the top of our readme / documentation to the [openfl/openfl](https://github.com/openfl/openfl) repo is a great idea to resolve any confusion that may occur in the future. If that's reasonable to you, I'll make the PR and close the issue. I would be happy to have a follow up conversation on this as well (you can reach me at patrick.foley@intel.com)

**Comment by nanjizal** [comment]
with the debarkle of RedHat on twitter recently, there is definitely a feeling that IBM influence on opensource maybe rather misguided at the moment.
 
Many years ago I worked on an 'Intel-Sky' video microsite using Sandy3D with Haxe Flash, as flash becomes a retro aspect of internet history, Haxe still moves forward targetting c++ and js.  I have no idea what other haxe Intel has used within thier organisation probably more than you might imagine, but feel that this projects name choice definitely undermines a large representation of the Haxe community.  OpenFL 'Open Flash' remains one of the only tools that allows the easy and accessible use of the flash api, and opens the opportunity to target  mobile, desktop and web. 

Continuing to use OpenFL name is probably not in your best interests as you may end up with the wrath of thousands of FNF script kiddies that use OpenFL and HxFlixel or at least many annoying Friday Night Funkin' confused questions. OpenFL as a name has been associate with 'Open Flash' within the indie gaming community for years especially with developers that used to use Flash, for instance Unity's tech director came from Flash Papervision3D, as I remember doing has course in Amsterdam many years back, and he will no doubt associate OpenFL with Haxe. 
 
Patrick you should respect that the OpenFL Haxe game engine has been running for many years and really there is no reason it should suddenly add readme details everytime another project reuses it's name. I don't feel my original request was unreasonable for only your project to add a link to original OpenFL. The request was in light of your project having not researched names and being large, so it is only right you should clarify the orginal openfl project in your readme, which is a reasonable request, especially since Intel is probably currently on the AI advertising bandwagon at the moment and confusion is most lightly to hurt the OpenFL haxe project.
 
Really I still feel that is would be most appropiate if you were to modify your project name, as OpenFL is largely connected with 'Open Flash' api concept within the indie gaming community for many years, and I really do not see such clear reasoning for your project name choice, which seems just catchy but vague to your cause.

I appreciate that you may not represent Intel on this project directly but in light of the mistake, to continue using OpenFL name you should look into the possibility of getting Intel to provide some ongoing sponsorship for the Haxe OpenFL projects continuing development.

I think for any user of OpenFL haxe and there are games and applications using it for longer than your project existed the reuse of the name is most upsetting. While a mistake on your part I welcome your swift reply and I can not speak for OpenFL haxe organisation directly, but my feelings as a long time haxe community member are still of disappointment you have not gone further.

**Comment by joshtynjala** [comment]
> however your proposal to include a link at the top of our readme / documentation to the [openfl/openfl](https://github.com/openfl/openfl) repo is a great idea to resolve any confusion that may occur in the future. If that's reasonable to you, I'll make the PR and close the issue.

As another core maintainer of openfl/openfl, I believe that this is reasonable. Thank you.

Please understand that @nanjizal does not speak for the maintainers of openfl/openfl, and I wish that he had consulted with us before contacting you. While the overlapping name is unfortunate, I don't think that you should change the name of your project.

**Comment by nanjizal** [comment]
Patrick

please consider that FireFox was originally named differently but took the responsible position of not overshadowing other projects.

https://lwn.net/Articles/70221/

I do not feel it is really in Intel's interest to trade on opensouce credentials while it promotes internal developers opensouce projects that reuse a well known code ecosystem name. To do so feels much like the corporate Greenwash going on with green issues among many corporations, companies like the tag but don't full commit to the responsibility.

The name clash in this instance has already started to erode another opensource projects google and twitter presence.  I feel it is worth modifying your project name even when OpenFL.org are not insisiting, it is the right course for your project and the right thing to do.

I am sorry if there is any mistake on my behalf on miss represented OpenFL.org views in anyway, but feel my personal opposition to your project naming is for good reason and urge you to consider my request. I will always be honest with my opinions even if they are blunt or untactful.

Best Justin

**Comment by dimensionscape** [comment]
> @nanjizal and @Dimensionscape - Thank you for raising this concern. I'm a maintainer for the Open Federated Learning (OpenFL) project, and wanted to let you know that my team has been discussing this internally. Our developer communities have no overlap - ours is a AI/ML framework so there should be no confusion, however your proposal to include a link at the top of our readme / documentation to the [openfl/openfl](https://github.com/openfl/openfl) repo is a great idea to resolve any confusion that may occur in the future. If that's reasonable to you, I'll make the PR and close the issue. I would be happy to have a follow up conversation on this as well (you can reach me at [patrick.foley@intel.com](mailto:patrick.foley@intel.com))

Super helpful response. 

I've been aware of namespace conflict for a while now, and while it does hurt our SEO in some cases, it has largely been a non-issue. I really appreciate your willingness to compromise on a solution to avoid confusion! I'm going to go out on a limb here and assume that we onboard a lot more users(with more frequency - over 1 million downloads to date!) and more often than not, they are beginners in the programming spectrum. With this in mind, a sense of confusion is much more likely coming from our user base, especially when landing from a search engine query.

I have to respect and at least share some of @nanjizal's concern here as one of the users of our codebase since his frustration is at least somewhat merited, however, as mentioned, he does not represent openfl.org in any official capacity. It would have been nice to handle this privately and internally discuss the situation before reaching out to you all in regards to this, but here we are. 

If you would like to reference back to our repository in your readme, that would certainly be helpful and in our interest, but I would not like you to feel pressured to do so in light of this conversation. Feel free to close this issue at your discretion. 

If you have any questions or comment, you can contact me privately at chris@dimensionscape.com. 

Thanks!!
