### ISSUE TITLE
Error in following the "Configuring the Federation" tutorial

### ISSUE THREAD

**Issue by chanfm81** [intel/openfl#84]
Hi,

I am trying out "fx collaborator generate-cert-request -n COL.LABEL" from https://openfl.readthedocs.io/en/latest/running_the_federation.certificates.html and I got the below error:

![image](https://user-images.githubusercontent.com/28550728/118785037-0c559180-b8c3-11eb-8681-52592aeaa24b.png)

I am using the "keras_cnn_mnist" template.

How do I resolve the issue?

Thanks.

**Comment by alexey-gruzdev** [comment]
@chanfm81 are you running this from workspace folder? Maybe you miss `cd my_federation` command?

**Comment by chanfm81** [comment]
Thanks. The error is gone after executing the command in the "my_federation" folder.

However when I issue the last command for collaborator to connect to the aggregator (fx collaborator start -n one), I got the below log:
![image](https://user-images.githubusercontent.com/28550728/118945826-679d8780-b988-11eb-9ad6-6b2c045d16e6.png)

The aggregator has the below log:
![image](https://user-images.githubusercontent.com/28550728/118946149-b1866d80-b988-11eb-8534-f09237dce052.png)

I used "localhost" as the FQDN as below:
fx plan initialize -a localhost
fx aggregator generate-cert-request --fqdn localhost
fx aggregator certify --fqdn localhost

I did not use docker but used conda as the environment.

Any idea if the aggregator or the collaborator is problematic and how to resolve the connection?

Thanks.

**Comment by alexey-gruzdev** [comment]
@chanfm81 could you check please if you have any other `fx` processes running in the background? And re-test with a clean env installation? Sometimes it could happen if you have more than one aggregator running on the same machine.

**Comment by chanfm81** [comment]
Hi, 

Thanks for the reply.
I have tested on Ubuntu 18.04 and it works.
However when I test on Arch Linux, it is not working.

In both experiments which I have done, there is only 1 fx process running which I have verified by command "sudo lsof -i -P -n | grep LISTEN". The env is a fresh installation.

I am not sure if it is related to OS, hosts file, some ipv6 thing or others.

**Comment by alexey-gruzdev** [comment]
@chanfm81 okay, thanks for clarification. I don't know why we have problems on Arch Linux, maybe additional investigation is needed. However, since currently we officially support only Ubuntu's I believe we could close this.
