### ISSUE TITLE
No programmatic description of expandable elements in sidebar as being expandable, until/unless they are expanded

### ISSUE THREAD

**Issue by ChrisXKeroack** [intel/openfl#845]
**Describe the bug**
Screenreader user won't hear expandable elements in sidebar are expandable

**To Reproduce**
1. start a screenreader
2. https://openfl.readthedocs.io/en/latest/index.html 
3. TAB to 'Manual'

Notice: Element is not described as expandable

**Expected behavior**
Screenreader to be able to tell me that this is expandable and currently collapsed, e.g. via support for aria-expanded

**Screenshots**
![image](https://github.com/securefederatedai/openfl/assets/104644211/92ce17e8-f131-4242-a6bd-f24fbd5296cd)

**Desktop:**
This issue is not OS or browser specific, but for tracking purposes, testing was done on Win11, in Edge Version 114.0.1823.58 (Official build) (64-bit), and the screenreader in use was the common 3rd party screenreader NVDA (http://www.nvaccess.org).

**Smartphone:**
This issue is not device, OS, or browser specific.

**Additional context**
This is an accessibility issue, please annotate this bug with the 'accessibility' label.

**Comment by fstrr** [comment]
This is an issue with the [Read The Docs platform](https://github.com/readthedocs/readthedocs.org).

**Comment by theakshaypant** [comment]
Closing. As mentioned by @fstrr, this is an issue with [Read The Docs platform](https://github.com/readthedocs/readthedocs.org).
