### ISSUE TITLE
Create docstrings for all public functions and create OpenFL API Documentation

### ISSUE THREAD

**Issue by psfoley** [intel/openfl#893]
Most of OpenFL functions are documented already, but this task involves making sure that they are all complete and up to date. After that is done, suggest using `sphinx-apidoc` to automatically generate API documentation and this to the OpenFL documentation.

**Comment by manuelhsantana** [comment]
PR created:
https://github.com/securefederatedai/openfl/pull/900

**Comment by MasterSkepticista** [comment]
Merged #1005
