### ISSUE TITLE
Regarding aggregation in openfl

### ISSUE THREAD

**Issue by chanfm81** [intel/openfl#90]
Hi,

If we want to use privacy preserving technologies such as differential privacy in securing aggregation in openfl, are there any tutorials or class interfaces which we can override to include the added security?

Are there any tutorials or class interfaces in openfl in which custom aggregation algorithms can be included other than federated averaging? Edit: I just realize there is new documentation added to custom averaging at https://openfl.readthedocs.io/en/latest/overriding_agg_fn.html

Thanks.

**Comment by alexey-gruzdev** [comment]
@chanfm81 hi! Thanks for your interest in OpenFL. 
Regarding first question - currently, there is no interface for differential privacy, DP features are in plans. If you can come up with a proposal how to integrate it to OpenFL - it would be great initial point to kick off DP discussion.

Regarding second point - you are absolutely right - you can check out the example [here](https://github.com/intel/openfl/blob/develop/openfl-tutorials/Federated_Pytorch_MNIST_custom_aggregation_Tutorial.ipynb) :)

**Comment by alexey-gruzdev** [comment]
@chanfm81 since I believe the question is answered I would close the issue.
