### ISSUE TITLE
Aggregator freezing with `gramine-sgx` for `torch_cnn_histology_gramine_ready`

### ISSUE THREAD

**Issue by psfoley** [intel/openfl#927]
User in slack channel reported issue related to aggregator freezing when using `gramine-sgx`. Closure of this task involves:
- Reproducing behavior
- If confirmed issue, implement fix
- If not reproduced, work with user to resolve their problem

[Slack Message](https://openfl.slack.com/archives/C02LQML0RU0/p1707839449814309?thread_ts=1707839449.814309&cid=C02LQML0RU0)

**Comment by teoparvanov** [comment]
This workspace has been removed as part of a broader refactoring of graminization for OpenFL.
