### ISSUE TITLE
Connection issue between collaborator and aggregator

### ISSUE THREAD

**Issue by saransh09** [intel/openfl#97]
In some machines, when I run a federation (even if it both the collaborators and the aggregator are on the same machine) they fail to establish a connection.
I have started facing this problem specifically in the interactive API, I have been unsuccessful in running a federation as collaborator is unable to connect to the port where aggregator has started the gRPC server.

Reproducing the error:
I did not do anything differently than what is already mentioned in the tutorial. 
I created a fresh conda environment, installed the openfl library and finally tried to replicate the experiment.

We tried to debug this error and in the process we found out that the gRPC server from the aggregator runs exclusively on IPv6. Whereas, collaborator tries to listen to IPv4. We even tried to hardcode the server and the port numbers but we were unable to make it work. We suspect that the error has something to do with the way the gRPC server are started in  https://github.com/intel/openfl/blob/c3c0886aefeb09f426fc3726be0f65de2b344e22/openfl/transport/grpc/server.py and https://github.com/intel/openfl/blob/c3c0886aefeb09f426fc3726be0f65de2b344e22/openfl/transport/grpc/client.py

I think this error can pose a potentially big problem in the future. Therefore, please look into it.

Thanks

**Comment by alexey-gruzdev** [comment]
@saransh09 could you please send us a log which you see when failing happens?

**Comment by mansishr** [comment]
@saransh09 could you try checking if the no_proxy settings are correct? I faced a similar issue which got resolved with export no_proxy=localhost on the terminal where you are running the collaborators.

**Comment by saransh09** [comment]
Hi Alexey and Mansi,
I tried to debug this issue with Igor. We tried everything from 'localhost', None, also tried to provide with the FQDN of the collaborator node in the field.

**Comment by mansishr** [comment]
Hi Saransh,

Is the aggregator still running on IPv6? If so, I disabled IPv6 on my machine (sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1)

**Comment by saransh09** [comment]
Last time we checked that was the case.
I am running it on IMU lab machines, and I don't have sudo rights to do this. However, I will try to discuss this.
Is this the only workaround available right now?

**Comment by alexey-gruzdev** [comment]
The problem resolved with:
```
export http_proxy=<your_http_proxy>
export https_proxy=<your_https_proxy>
export no_proxy=localhost

```

**Comment by adityarastogi2k12** [comment]
Hi @saransh09 , did you find a solution to this problem?

**Comment by BenjaminAcar** [comment]
Have the same problem. Handshake failed, even if I run everything on one machine. Any solutions for that?

**Comment by saransh09** [comment]
> Have the same problem. Handshake failed, even if I run everything on one machine. Any solutions for that?

sorry it has been quite some time, so I don't remember the specifics. However, just putting what Alexey suggested in the terminal / bashrc solved the issue for me.

Note that OpenFL might have changed since that time, because I have not looked into the framework in a long long time now.

**Comment by BenjaminAcar** [comment]
But I have no proxys running on my machines, what shall I use for http_proxy/https_proxy? localhost?

**Comment by vinaBira** [comment]
Hello I am also facing the same error @BenjaminAcar Did you able to solve the error?

**Comment by BenjaminAcar** [comment]
https://youtu.be/9R3MnmjifuE

Here

**Comment by vinaBira** [comment]
@BenjaminAcar Already tried it without TLS certificate still facing the same error.
Here are some details: Trying on multiple nodes aggregator is gpu machine and collaborator is jetson nano
Can you please help me with understanding and guiding it through?

**Comment by BenjaminAcar** [comment]
Did you checked whether the ports for the traffic are blocked ?
That could cause the issue as well
If you run your federation on multiple Machines.

And also be careful that the FQDN in your config file is correct

**Comment by vinaBira** [comment]
@BenjaminAcar Done all of these as well created new firewall and opened it to everywhere.
Aslo FQDN setup is correct.
If possible, 
Can you please connect and take a look ?

**Comment by BenjaminAcar** [comment]
Send your config files, I will have a look on them

**Comment by vinaBira** [comment]
I was not able to ping the aggregator from collaborators devices (ping <HOSTNAME_FQDN>).
made changes in /etc/hosts/ accordingly. 
It is working now.
@BenjaminAcar Thank you so much for offering kind help!

**Comment by BenjaminAcar** [comment]
> I was not able to ping the aggregator from collaborators devices (ping <HOSTNAME_FQDN>).
> made changes in /etc/hosts/ accordingly. 
> It is working now.
> @BenjaminAcar Thank you so much for offering kind help!

You are Welcome
