### ISSUE TITLE
Fix Lint Errors: Remove ModelHeader and TensorProto in experimental protocols

### ISSUE THREAD

**Issue by psfoley** [intel/openfl#984]
./openfl/experimental/protocols/utils.py:46:20: F821 undefined name 'ModelHeader'
    model_header = ModelHeader(
                   ^
./openfl/experimental/protocols/utils.py:77:13: F[8](https://github.com/securefederatedai/openfl/actions/runs/9398049127/job/25882583649?pr=980#step:5:9)21 undefined name 'TensorProto'
            TensorProto(
            ^

**Comment by MasterSkepticista** [comment]
Fixed in #998
